---
apiVersion: storage.simplyblock.io/v1alpha1
kind: VolumeMigration
metadata:
  name: test-migration
  namespace: default
spec:
  # PV name whose backing logical volume should be migrated.
  pvName: pvc-968cff4f-a199-4964-88f0-7cfccb5251d9
  # UUID of the destination storage node.
  targetNodeUUID: 4e53efdd-86c9-424f-940c-e437eb6a2e95
