apiVersion: storage.simplyblock.io/v1alpha2
kind: ClusterDeploymentConfig
metadata:
  creationTimestamp: "2026-09-15T13:55:35Z"
  generation: 1
  labels:
    storage.simplyblock.io/component: nodeprobe
    storage.simplyblock.io/nodeprobe-run: initial-discovery
  name: discovered-initial-discovery
  namespace: simplyblock
  resourceVersion: "14949006"
  uid: 4c99c053-c94e-44c2-88bb-e76bf37c3357
spec:
  cluster:
    maxSubsystemCount: 30
    name: discovered-initial-discovery-cluster
    vcpuCount: 4
  environment: K3s
  nodeSets:
  - groups:
    - devices:
        nvme:
        - "0000:00:02.0"
        - "0000:00:03.0"
        - "0000:00:04.0"
        - "0000:00:05.0"
      name: group-1-nvme-4xunsized
      workers:
      - vm02.simplyblock4.localdomain
      - vm03.simplyblock4.localdomain
      - vm04.simplyblock4.localdomain
    name: discovered
