// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nvme.proto

// Package atlas.storage.v1 exposes a node's local NVMe state to the operator over
// a link.
//
// The messages mirror the snapshot types in the atlas nvme package field for
// field. That is deliberate and worth preserving: those types are immutable
// scans of sysfs with no behaviour attached, so the wire form can be a complete
// copy rather than a summary, and a caller on the far side of a link gets the
// same answers -- including the derived ones like Device.Accessible, which is a
// pure function of the fields carried here -- as a caller on the node.
//
// Everything here is read-only. Attaching and detaching fabrics is a separate,
// mutating service, so that a credential can be granted this and not that.

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address is a parsed NVMe-oF controller address.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Traddr        string                 `protobuf:"bytes,1,opt,name=traddr,proto3" json:"traddr,omitempty"`                  // target transport address
	Trsvcid       string                 `protobuf:"bytes,2,opt,name=trsvcid,proto3" json:"trsvcid,omitempty"`                // target service id (port)
	SrcAddr       string                 `protobuf:"bytes,3,opt,name=src_addr,json=srcAddr,proto3" json:"src_addr,omitempty"` // host source address; may be empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_nvme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetTraddr() string {
	if x != nil {
		return x.Traddr
	}
	return ""
}

func (x *Address) GetTrsvcid() string {
	if x != nil {
		return x.Trsvcid
	}
	return ""
}

func (x *Address) GetSrcAddr() string {
	if x != nil {
		return x.SrcAddr
	}
	return ""
}

// Controller is one path into a subsystem.
type Controller struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "nvme0"
	SysfsPath         string                 `protobuf:"bytes,2,opt,name=sysfs_path,json=sysfsPath,proto3" json:"sysfs_path,omitempty"`
	DevicePath        string                 `protobuf:"bytes,3,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"` // "/dev/nvme0" (char/admin device)
	Dev               string                 `protobuf:"bytes,4,opt,name=dev,proto3" json:"dev,omitempty"`                                 // "major:minor"
	Nqn               string                 `protobuf:"bytes,5,opt,name=nqn,proto3" json:"nqn,omitempty"`
	Cntlid            uint32                 `protobuf:"varint,6,opt,name=cntlid,proto3" json:"cntlid,omitempty"`      // controller id within the subsystem
	Type              string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`           // "io", "discovery", "admin"
	Transport         string                 `protobuf:"bytes,8,opt,name=transport,proto3" json:"transport,omitempty"` // "tcp", "rdma", "fc", "pcie"
	State             string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"`         // "live", "connecting", "resetting"
	Address           *Address               `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	HostNqn           string                 `protobuf:"bytes,11,opt,name=host_nqn,json=hostNqn,proto3" json:"host_nqn,omitempty"`
	HostId            string                 `protobuf:"bytes,12,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	NumaNode          int32                  `protobuf:"varint,13,opt,name=numa_node,json=numaNode,proto3" json:"numa_node,omitempty"` // -1 when unset
	QueueCount        int32                  `protobuf:"varint,14,opt,name=queue_count,json=queueCount,proto3" json:"queue_count,omitempty"`
	SqSize            int32                  `protobuf:"varint,15,opt,name=sq_size,json=sqSize,proto3" json:"sq_size,omitempty"`
	KeepAliveToSec    int32                  `protobuf:"varint,16,opt,name=keep_alive_to_sec,json=keepAliveToSec,proto3" json:"keep_alive_to_sec,omitempty"`
	CtrlLossTmoSec    int32                  `protobuf:"varint,17,opt,name=ctrl_loss_tmo_sec,json=ctrlLossTmoSec,proto3" json:"ctrl_loss_tmo_sec,omitempty"`
	ReconnectDelaySec int32                  `protobuf:"varint,18,opt,name=reconnect_delay_sec,json=reconnectDelaySec,proto3" json:"reconnect_delay_sec,omitempty"`
	FastIoFailTmo     string                 `protobuf:"bytes,19,opt,name=fast_io_fail_tmo,json=fastIoFailTmo,proto3" json:"fast_io_fail_tmo,omitempty"` // "off" or seconds
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Controller) Reset() {
	*x = Controller{}
	mi := &file_nvme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Controller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Controller) ProtoMessage() {}

func (x *Controller) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Controller.ProtoReflect.Descriptor instead.
func (*Controller) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{1}
}

func (x *Controller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Controller) GetSysfsPath() string {
	if x != nil {
		return x.SysfsPath
	}
	return ""
}

func (x *Controller) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *Controller) GetDev() string {
	if x != nil {
		return x.Dev
	}
	return ""
}

func (x *Controller) GetNqn() string {
	if x != nil {
		return x.Nqn
	}
	return ""
}

func (x *Controller) GetCntlid() uint32 {
	if x != nil {
		return x.Cntlid
	}
	return 0
}

func (x *Controller) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Controller) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *Controller) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Controller) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Controller) GetHostNqn() string {
	if x != nil {
		return x.HostNqn
	}
	return ""
}

func (x *Controller) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *Controller) GetNumaNode() int32 {
	if x != nil {
		return x.NumaNode
	}
	return 0
}

func (x *Controller) GetQueueCount() int32 {
	if x != nil {
		return x.QueueCount
	}
	return 0
}

func (x *Controller) GetSqSize() int32 {
	if x != nil {
		return x.SqSize
	}
	return 0
}

func (x *Controller) GetKeepAliveToSec() int32 {
	if x != nil {
		return x.KeepAliveToSec
	}
	return 0
}

func (x *Controller) GetCtrlLossTmoSec() int32 {
	if x != nil {
		return x.CtrlLossTmoSec
	}
	return 0
}

func (x *Controller) GetReconnectDelaySec() int32 {
	if x != nil {
		return x.ReconnectDelaySec
	}
	return 0
}

func (x *Controller) GetFastIoFailTmo() string {
	if x != nil {
		return x.FastIoFailTmo
	}
	return ""
}

// Path is one controller's access path to a namespace, carrying the ANA state
// that says whether I/O may travel over it.
type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Controller    string                 `protobuf:"bytes,1,opt,name=controller,proto3" json:"controller,omitempty"` // owning controller, e.g. "nvme1"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`             // leg name, e.g. "nvme0c1n1"
	SysfsPath     string                 `protobuf:"bytes,3,opt,name=sysfs_path,json=sysfsPath,proto3" json:"sysfs_path,omitempty"`
	Nsid          uint32                 `protobuf:"varint,4,opt,name=nsid,proto3" json:"nsid,omitempty"`
	AnaState      string                 `protobuf:"bytes,5,opt,name=ana_state,json=anaState,proto3" json:"ana_state,omitempty"` // "optimized", "non-optimized", "inaccessible", ...
	AnaGroupId    uint32                 `protobuf:"varint,6,opt,name=ana_group_id,json=anaGroupId,proto3" json:"ana_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_nvme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{2}
}

func (x *Path) GetController() string {
	if x != nil {
		return x.Controller
	}
	return ""
}

func (x *Path) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Path) GetSysfsPath() string {
	if x != nil {
		return x.SysfsPath
	}
	return ""
}

func (x *Path) GetNsid() uint32 {
	if x != nil {
		return x.Nsid
	}
	return 0
}

func (x *Path) GetAnaState() string {
	if x != nil {
		return x.AnaState
	}
	return ""
}

func (x *Path) GetAnaGroupId() uint32 {
	if x != nil {
		return x.AnaGroupId
	}
	return 0
}

// Namespace is a block namespace exported by a subsystem.
type Namespace struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // nsid
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // "nvme0n1"
	SysfsPath        string                 `protobuf:"bytes,3,opt,name=sysfs_path,json=sysfsPath,proto3" json:"sysfs_path,omitempty"`
	DevicePath       string                 `protobuf:"bytes,4,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"` // "/dev/nvme0n1"
	Dev              string                 `protobuf:"bytes,5,opt,name=dev,proto3" json:"dev,omitempty"`                                 // "major:minor"
	Uuid             string                 `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`                               // simplyblock: the lvol UUID
	Nguid            string                 `protobuf:"bytes,7,opt,name=nguid,proto3" json:"nguid,omitempty"`
	Wwid             string                 `protobuf:"bytes,8,opt,name=wwid,proto3" json:"wwid,omitempty"`
	Csi              int32                  `protobuf:"varint,9,opt,name=csi,proto3" json:"csi,omitempty"`                                                      // command set identifier (0 = NVM)
	LogicalBlockSize uint32                 `protobuf:"varint,10,opt,name=logical_block_size,json=logicalBlockSize,proto3" json:"logical_block_size,omitempty"` // bytes
	// capacity and used are in 512-byte sectors, independent of
	// logical_block_size.
	Capacity      uint64 `protobuf:"varint,11,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Used          uint64 `protobuf:"varint,12,opt,name=used,proto3" json:"used,omitempty"`
	MetadataBytes uint32 `protobuf:"varint,13,opt,name=metadata_bytes,json=metadataBytes,proto3" json:"metadata_bytes,omitempty"`
	ReadOnly      bool   `protobuf:"varint,14,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Hidden        bool   `protobuf:"varint,15,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// paths is the per-controller ANA view. Empty for non-multipath devices.
	Paths []*Path `protobuf:"bytes,16,rep,name=paths,proto3" json:"paths,omitempty"`
	// controller names the single owning controller, set only where the kernel
	// exposes no multipath head and the namespace is one controller's private
	// block device. Empty for a multipath head.
	Controller    string `protobuf:"bytes,17,opt,name=controller,proto3" json:"controller,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_nvme_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{3}
}

func (x *Namespace) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetSysfsPath() string {
	if x != nil {
		return x.SysfsPath
	}
	return ""
}

func (x *Namespace) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *Namespace) GetDev() string {
	if x != nil {
		return x.Dev
	}
	return ""
}

func (x *Namespace) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Namespace) GetNguid() string {
	if x != nil {
		return x.Nguid
	}
	return ""
}

func (x *Namespace) GetWwid() string {
	if x != nil {
		return x.Wwid
	}
	return ""
}

func (x *Namespace) GetCsi() int32 {
	if x != nil {
		return x.Csi
	}
	return 0
}

func (x *Namespace) GetLogicalBlockSize() uint32 {
	if x != nil {
		return x.LogicalBlockSize
	}
	return 0
}

func (x *Namespace) GetCapacity() uint64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Namespace) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *Namespace) GetMetadataBytes() uint32 {
	if x != nil {
		return x.MetadataBytes
	}
	return 0
}

func (x *Namespace) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *Namespace) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Namespace) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Namespace) GetController() string {
	if x != nil {
		return x.Controller
	}
	return ""
}

// Subsystem is an NVMe subsystem: the unit a simplyblock logical volume maps
// to, fronted by one or more controllers and exporting one or more namespaces.
type Subsystem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "nvme-subsys0"
	SysfsPath     string                 `protobuf:"bytes,2,opt,name=sysfs_path,json=sysfsPath,proto3" json:"sysfs_path,omitempty"`
	Nqn           string                 `protobuf:"bytes,3,opt,name=nqn,proto3" json:"nqn,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"` // simplyblock encodes the lvol UUID here
	Serial        string                 `protobuf:"bytes,5,opt,name=serial,proto3" json:"serial,omitempty"`
	FirmwareRev   string                 `protobuf:"bytes,6,opt,name=firmware_rev,json=firmwareRev,proto3" json:"firmware_rev,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`                         // "nvm", "discovery"
	IoPolicy      string                 `protobuf:"bytes,8,opt,name=io_policy,json=ioPolicy,proto3" json:"io_policy,omitempty"` // "numa", "round-robin", "queue-depth"
	Controllers   []*Controller          `protobuf:"bytes,9,rep,name=controllers,proto3" json:"controllers,omitempty"`
	Namespaces    []*Namespace           `protobuf:"bytes,10,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subsystem) Reset() {
	*x = Subsystem{}
	mi := &file_nvme_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subsystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subsystem) ProtoMessage() {}

func (x *Subsystem) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subsystem.ProtoReflect.Descriptor instead.
func (*Subsystem) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{4}
}

func (x *Subsystem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subsystem) GetSysfsPath() string {
	if x != nil {
		return x.SysfsPath
	}
	return ""
}

func (x *Subsystem) GetNqn() string {
	if x != nil {
		return x.Nqn
	}
	return ""
}

func (x *Subsystem) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Subsystem) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Subsystem) GetFirmwareRev() string {
	if x != nil {
		return x.FirmwareRev
	}
	return ""
}

func (x *Subsystem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Subsystem) GetIoPolicy() string {
	if x != nil {
		return x.IoPolicy
	}
	return ""
}

func (x *Subsystem) GetControllers() []*Controller {
	if x != nil {
		return x.Controllers
	}
	return nil
}

func (x *Subsystem) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

// Device is a namespace together with the subsystem exporting it -- the unit a
// CSI NodeStage/NodePublish acts on.
type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Subsystem     *Subsystem             `protobuf:"bytes,2,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_nvme_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{5}
}

func (x *Device) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *Device) GetSubsystem() *Subsystem {
	if x != nil {
		return x.Subsystem
	}
	return nil
}

// DeviceSelector narrows a set of devices. Every field is optional and all set
// fields are ANDed, so an unset selector matches everything.
type DeviceSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nqn           string                 `protobuf:"bytes,1,opt,name=nqn,proto3" json:"nqn,omitempty"`
	Nsid          uint32                 `protobuf:"varint,2,opt,name=nsid,proto3" json:"nsid,omitempty"` // 0: any
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	DevicePath    string                 `protobuf:"bytes,4,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSelector) Reset() {
	*x = DeviceSelector{}
	mi := &file_nvme_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSelector) ProtoMessage() {}

func (x *DeviceSelector) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSelector.ProtoReflect.Descriptor instead.
func (*DeviceSelector) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceSelector) GetNqn() string {
	if x != nil {
		return x.Nqn
	}
	return ""
}

func (x *DeviceSelector) GetNsid() uint32 {
	if x != nil {
		return x.Nsid
	}
	return 0
}

func (x *DeviceSelector) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DeviceSelector) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

type ListSubsystemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubsystemsRequest) Reset() {
	*x = ListSubsystemsRequest{}
	mi := &file_nvme_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubsystemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubsystemsRequest) ProtoMessage() {}

func (x *ListSubsystemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubsystemsRequest.ProtoReflect.Descriptor instead.
func (*ListSubsystemsRequest) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{7}
}

type ListSubsystemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subsystems    []*Subsystem           `protobuf:"bytes,1,rep,name=subsystems,proto3" json:"subsystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubsystemsResponse) Reset() {
	*x = ListSubsystemsResponse{}
	mi := &file_nvme_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubsystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubsystemsResponse) ProtoMessage() {}

func (x *ListSubsystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubsystemsResponse.ProtoReflect.Descriptor instead.
func (*ListSubsystemsResponse) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{8}
}

func (x *ListSubsystemsResponse) GetSubsystems() []*Subsystem {
	if x != nil {
		return x.Subsystems
	}
	return nil
}

type GetSubsystemByNQNRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nqn           string                 `protobuf:"bytes,1,opt,name=nqn,proto3" json:"nqn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubsystemByNQNRequest) Reset() {
	*x = GetSubsystemByNQNRequest{}
	mi := &file_nvme_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubsystemByNQNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubsystemByNQNRequest) ProtoMessage() {}

func (x *GetSubsystemByNQNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubsystemByNQNRequest.ProtoReflect.Descriptor instead.
func (*GetSubsystemByNQNRequest) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{9}
}

func (x *GetSubsystemByNQNRequest) GetNqn() string {
	if x != nil {
		return x.Nqn
	}
	return ""
}

type GetSubsystemByNQNResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subsystem     *Subsystem             `protobuf:"bytes,1,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubsystemByNQNResponse) Reset() {
	*x = GetSubsystemByNQNResponse{}
	mi := &file_nvme_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubsystemByNQNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubsystemByNQNResponse) ProtoMessage() {}

func (x *GetSubsystemByNQNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubsystemByNQNResponse.ProtoReflect.Descriptor instead.
func (*GetSubsystemByNQNResponse) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{10}
}

func (x *GetSubsystemByNQNResponse) GetSubsystem() *Subsystem {
	if x != nil {
		return x.Subsystem
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_nvme_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{11}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_nvme_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{12}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ListDevicesBySelectorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *DeviceSelector        `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesBySelectorRequest) Reset() {
	*x = ListDevicesBySelectorRequest{}
	mi := &file_nvme_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesBySelectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesBySelectorRequest) ProtoMessage() {}

func (x *ListDevicesBySelectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesBySelectorRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesBySelectorRequest) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{13}
}

func (x *ListDevicesBySelectorRequest) GetSelector() *DeviceSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type ListDevicesBySelectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesBySelectorResponse) Reset() {
	*x = ListDevicesBySelectorResponse{}
	mi := &file_nvme_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesBySelectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesBySelectorResponse) ProtoMessage() {}

func (x *ListDevicesBySelectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesBySelectorResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesBySelectorResponse) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{14}
}

func (x *ListDevicesBySelectorResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDeviceByUUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByUUIDRequest) Reset() {
	*x = GetDeviceByUUIDRequest{}
	mi := &file_nvme_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByUUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByUUIDRequest) ProtoMessage() {}

func (x *GetDeviceByUUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByUUIDRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceByUUIDRequest) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{15}
}

func (x *GetDeviceByUUIDRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetDeviceByUUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByUUIDResponse) Reset() {
	*x = GetDeviceByUUIDResponse{}
	mi := &file_nvme_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByUUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByUUIDResponse) ProtoMessage() {}

func (x *GetDeviceByUUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByUUIDResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceByUUIDResponse) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{16}
}

func (x *GetDeviceByUUIDResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDeviceByDevicePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DevicePath    string                 `protobuf:"bytes,1,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByDevicePathRequest) Reset() {
	*x = GetDeviceByDevicePathRequest{}
	mi := &file_nvme_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByDevicePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByDevicePathRequest) ProtoMessage() {}

func (x *GetDeviceByDevicePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByDevicePathRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceByDevicePathRequest) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{17}
}

func (x *GetDeviceByDevicePathRequest) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

type GetDeviceByDevicePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByDevicePathResponse) Reset() {
	*x = GetDeviceByDevicePathResponse{}
	mi := &file_nvme_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByDevicePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByDevicePathResponse) ProtoMessage() {}

func (x *GetDeviceByDevicePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByDevicePathResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceByDevicePathResponse) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{18}
}

func (x *GetDeviceByDevicePathResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDeviceByNamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nqn           string                 `protobuf:"bytes,1,opt,name=nqn,proto3" json:"nqn,omitempty"`
	Nsid          uint32                 `protobuf:"varint,2,opt,name=nsid,proto3" json:"nsid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByNamespaceRequest) Reset() {
	*x = GetDeviceByNamespaceRequest{}
	mi := &file_nvme_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByNamespaceRequest) ProtoMessage() {}

func (x *GetDeviceByNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByNamespaceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceByNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{19}
}

func (x *GetDeviceByNamespaceRequest) GetNqn() string {
	if x != nil {
		return x.Nqn
	}
	return ""
}

func (x *GetDeviceByNamespaceRequest) GetNsid() uint32 {
	if x != nil {
		return x.Nsid
	}
	return 0
}

type GetDeviceByNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceByNamespaceResponse) Reset() {
	*x = GetDeviceByNamespaceResponse{}
	mi := &file_nvme_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceByNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceByNamespaceResponse) ProtoMessage() {}

func (x *GetDeviceByNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nvme_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceByNamespaceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceByNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_nvme_proto_rawDescGZIP(), []int{20}
}

func (x *GetDeviceByNamespaceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

var File_nvme_proto protoreflect.FileDescriptor

const file_nvme_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"nvme.proto\x12\x10atlas.storage.v1\"V\n" +
	"\aAddress\x12\x16\n" +
	"\x06traddr\x18\x01 \x01(\tR\x06traddr\x12\x18\n" +
	"\atrsvcid\x18\x02 \x01(\tR\atrsvcid\x12\x19\n" +
	"\bsrc_addr\x18\x03 \x01(\tR\asrcAddr\"\xcf\x04\n" +
	"\n" +
	"Controller\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"sysfs_path\x18\x02 \x01(\tR\tsysfsPath\x12\x1f\n" +
	"\vdevice_path\x18\x03 \x01(\tR\n" +
	"devicePath\x12\x10\n" +
	"\x03dev\x18\x04 \x01(\tR\x03dev\x12\x10\n" +
	"\x03nqn\x18\x05 \x01(\tR\x03nqn\x12\x16\n" +
	"\x06cntlid\x18\x06 \x01(\rR\x06cntlid\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1c\n" +
	"\ttransport\x18\b \x01(\tR\ttransport\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x123\n" +
	"\aaddress\x18\n" +
	" \x01(\v2\x19.atlas.storage.v1.AddressR\aaddress\x12\x19\n" +
	"\bhost_nqn\x18\v \x01(\tR\ahostNqn\x12\x17\n" +
	"\ahost_id\x18\f \x01(\tR\x06hostId\x12\x1b\n" +
	"\tnuma_node\x18\r \x01(\x05R\bnumaNode\x12\x1f\n" +
	"\vqueue_count\x18\x0e \x01(\x05R\n" +
	"queueCount\x12\x17\n" +
	"\asq_size\x18\x0f \x01(\x05R\x06sqSize\x12)\n" +
	"\x11keep_alive_to_sec\x18\x10 \x01(\x05R\x0ekeepAliveToSec\x12)\n" +
	"\x11ctrl_loss_tmo_sec\x18\x11 \x01(\x05R\x0ectrlLossTmoSec\x12.\n" +
	"\x13reconnect_delay_sec\x18\x12 \x01(\x05R\x11reconnectDelaySec\x12'\n" +
	"\x10fast_io_fail_tmo\x18\x13 \x01(\tR\rfastIoFailTmo\"\xac\x01\n" +
	"\x04Path\x12\x1e\n" +
	"\n" +
	"controller\x18\x01 \x01(\tR\n" +
	"controller\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sysfs_path\x18\x03 \x01(\tR\tsysfsPath\x12\x12\n" +
	"\x04nsid\x18\x04 \x01(\rR\x04nsid\x12\x1b\n" +
	"\tana_state\x18\x05 \x01(\tR\banaState\x12 \n" +
	"\fana_group_id\x18\x06 \x01(\rR\n" +
	"anaGroupId\"\xd9\x03\n" +
	"\tNamespace\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sysfs_path\x18\x03 \x01(\tR\tsysfsPath\x12\x1f\n" +
	"\vdevice_path\x18\x04 \x01(\tR\n" +
	"devicePath\x12\x10\n" +
	"\x03dev\x18\x05 \x01(\tR\x03dev\x12\x12\n" +
	"\x04uuid\x18\x06 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05nguid\x18\a \x01(\tR\x05nguid\x12\x12\n" +
	"\x04wwid\x18\b \x01(\tR\x04wwid\x12\x10\n" +
	"\x03csi\x18\t \x01(\x05R\x03csi\x12,\n" +
	"\x12logical_block_size\x18\n" +
	" \x01(\rR\x10logicalBlockSize\x12\x1a\n" +
	"\bcapacity\x18\v \x01(\x04R\bcapacity\x12\x12\n" +
	"\x04used\x18\f \x01(\x04R\x04used\x12%\n" +
	"\x0emetadata_bytes\x18\r \x01(\rR\rmetadataBytes\x12\x1b\n" +
	"\tread_only\x18\x0e \x01(\bR\breadOnly\x12\x16\n" +
	"\x06hidden\x18\x0f \x01(\bR\x06hidden\x12,\n" +
	"\x05paths\x18\x10 \x03(\v2\x16.atlas.storage.v1.PathR\x05paths\x12\x1e\n" +
	"\n" +
	"controller\x18\x11 \x01(\tR\n" +
	"controller\"\xcb\x02\n" +
	"\tSubsystem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"sysfs_path\x18\x02 \x01(\tR\tsysfsPath\x12\x10\n" +
	"\x03nqn\x18\x03 \x01(\tR\x03nqn\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x16\n" +
	"\x06serial\x18\x05 \x01(\tR\x06serial\x12!\n" +
	"\ffirmware_rev\x18\x06 \x01(\tR\vfirmwareRev\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1b\n" +
	"\tio_policy\x18\b \x01(\tR\bioPolicy\x12>\n" +
	"\vcontrollers\x18\t \x03(\v2\x1c.atlas.storage.v1.ControllerR\vcontrollers\x12;\n" +
	"\n" +
	"namespaces\x18\n" +
	" \x03(\v2\x1b.atlas.storage.v1.NamespaceR\n" +
	"namespaces\"~\n" +
	"\x06Device\x129\n" +
	"\tnamespace\x18\x01 \x01(\v2\x1b.atlas.storage.v1.NamespaceR\tnamespace\x129\n" +
	"\tsubsystem\x18\x02 \x01(\v2\x1b.atlas.storage.v1.SubsystemR\tsubsystem\"k\n" +
	"\x0eDeviceSelector\x12\x10\n" +
	"\x03nqn\x18\x01 \x01(\tR\x03nqn\x12\x12\n" +
	"\x04nsid\x18\x02 \x01(\rR\x04nsid\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vdevice_path\x18\x04 \x01(\tR\n" +
	"devicePath\"\x17\n" +
	"\x15ListSubsystemsRequest\"U\n" +
	"\x16ListSubsystemsResponse\x12;\n" +
	"\n" +
	"subsystems\x18\x01 \x03(\v2\x1b.atlas.storage.v1.SubsystemR\n" +
	"subsystems\",\n" +
	"\x18GetSubsystemByNQNRequest\x12\x10\n" +
	"\x03nqn\x18\x01 \x01(\tR\x03nqn\"V\n" +
	"\x19GetSubsystemByNQNResponse\x129\n" +
	"\tsubsystem\x18\x01 \x01(\v2\x1b.atlas.storage.v1.SubsystemR\tsubsystem\"\x14\n" +
	"\x12ListDevicesRequest\"I\n" +
	"\x13ListDevicesResponse\x122\n" +
	"\adevices\x18\x01 \x03(\v2\x18.atlas.storage.v1.DeviceR\adevices\"\\\n" +
	"\x1cListDevicesBySelectorRequest\x12<\n" +
	"\bselector\x18\x01 \x01(\v2 .atlas.storage.v1.DeviceSelectorR\bselector\"S\n" +
	"\x1dListDevicesBySelectorResponse\x122\n" +
	"\adevices\x18\x01 \x03(\v2\x18.atlas.storage.v1.DeviceR\adevices\",\n" +
	"\x16GetDeviceByUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"K\n" +
	"\x17GetDeviceByUUIDResponse\x120\n" +
	"\x06device\x18\x01 \x01(\v2\x18.atlas.storage.v1.DeviceR\x06device\"?\n" +
	"\x1cGetDeviceByDevicePathRequest\x12\x1f\n" +
	"\vdevice_path\x18\x01 \x01(\tR\n" +
	"devicePath\"Q\n" +
	"\x1dGetDeviceByDevicePathResponse\x120\n" +
	"\x06device\x18\x01 \x01(\v2\x18.atlas.storage.v1.DeviceR\x06device\"C\n" +
	"\x1bGetDeviceByNamespaceRequest\x12\x10\n" +
	"\x03nqn\x18\x01 \x01(\tR\x03nqn\x12\x12\n" +
	"\x04nsid\x18\x02 \x01(\rR\x04nsid\"P\n" +
	"\x1cGetDeviceByNamespaceResponse\x120\n" +
	"\x06device\x18\x01 \x01(\v2\x18.atlas.storage.v1.DeviceR\x06device2\xe5\x01\n" +
	"\x10SubsystemService\x12c\n" +
	"\x0eListSubsystems\x12'.atlas.storage.v1.ListSubsystemsRequest\x1a(.atlas.storage.v1.ListSubsystemsResponse\x12l\n" +
	"\x11GetSubsystemByNQN\x12*.atlas.storage.v1.GetSubsystemByNQNRequest\x1a+.atlas.storage.v1.GetSubsystemByNQNResponse2\xbe\x04\n" +
	"\rDeviceService\x12Z\n" +
	"\vListDevices\x12$.atlas.storage.v1.ListDevicesRequest\x1a%.atlas.storage.v1.ListDevicesResponse\x12x\n" +
	"\x15ListDevicesBySelector\x12..atlas.storage.v1.ListDevicesBySelectorRequest\x1a/.atlas.storage.v1.ListDevicesBySelectorResponse\x12f\n" +
	"\x0fGetDeviceByUUID\x12(.atlas.storage.v1.GetDeviceByUUIDRequest\x1a).atlas.storage.v1.GetDeviceByUUIDResponse\x12x\n" +
	"\x15GetDeviceByDevicePath\x12..atlas.storage.v1.GetDeviceByDevicePathRequest\x1a/.atlas.storage.v1.GetDeviceByDevicePathResponse\x12u\n" +
	"\x14GetDeviceByNamespace\x12-.atlas.storage.v1.GetDeviceByNamespaceRequest\x1a..atlas.storage.v1.GetDeviceByNamespaceResponseBEZCgithub.com/simplyblock/atlas/storage/storagerpc/storagev1;storagev1b\x06proto3"

var (
	file_nvme_proto_rawDescOnce sync.Once
	file_nvme_proto_rawDescData []byte
)

func file_nvme_proto_rawDescGZIP() []byte {
	file_nvme_proto_rawDescOnce.Do(func() {
		file_nvme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nvme_proto_rawDesc), len(file_nvme_proto_rawDesc)))
	})
	return file_nvme_proto_rawDescData
}

var file_nvme_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_nvme_proto_goTypes = []any{
	(*Address)(nil),                       // 0: atlas.storage.v1.Address
	(*Controller)(nil),                    // 1: atlas.storage.v1.Controller
	(*Path)(nil),                          // 2: atlas.storage.v1.Path
	(*Namespace)(nil),                     // 3: atlas.storage.v1.Namespace
	(*Subsystem)(nil),                     // 4: atlas.storage.v1.Subsystem
	(*Device)(nil),                        // 5: atlas.storage.v1.Device
	(*DeviceSelector)(nil),                // 6: atlas.storage.v1.DeviceSelector
	(*ListSubsystemsRequest)(nil),         // 7: atlas.storage.v1.ListSubsystemsRequest
	(*ListSubsystemsResponse)(nil),        // 8: atlas.storage.v1.ListSubsystemsResponse
	(*GetSubsystemByNQNRequest)(nil),      // 9: atlas.storage.v1.GetSubsystemByNQNRequest
	(*GetSubsystemByNQNResponse)(nil),     // 10: atlas.storage.v1.GetSubsystemByNQNResponse
	(*ListDevicesRequest)(nil),            // 11: atlas.storage.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),           // 12: atlas.storage.v1.ListDevicesResponse
	(*ListDevicesBySelectorRequest)(nil),  // 13: atlas.storage.v1.ListDevicesBySelectorRequest
	(*ListDevicesBySelectorResponse)(nil), // 14: atlas.storage.v1.ListDevicesBySelectorResponse
	(*GetDeviceByUUIDRequest)(nil),        // 15: atlas.storage.v1.GetDeviceByUUIDRequest
	(*GetDeviceByUUIDResponse)(nil),       // 16: atlas.storage.v1.GetDeviceByUUIDResponse
	(*GetDeviceByDevicePathRequest)(nil),  // 17: atlas.storage.v1.GetDeviceByDevicePathRequest
	(*GetDeviceByDevicePathResponse)(nil), // 18: atlas.storage.v1.GetDeviceByDevicePathResponse
	(*GetDeviceByNamespaceRequest)(nil),   // 19: atlas.storage.v1.GetDeviceByNamespaceRequest
	(*GetDeviceByNamespaceResponse)(nil),  // 20: atlas.storage.v1.GetDeviceByNamespaceResponse
}
var file_nvme_proto_depIdxs = []int32{
	0,  // 0: atlas.storage.v1.Controller.address:type_name -> atlas.storage.v1.Address
	2,  // 1: atlas.storage.v1.Namespace.paths:type_name -> atlas.storage.v1.Path
	1,  // 2: atlas.storage.v1.Subsystem.controllers:type_name -> atlas.storage.v1.Controller
	3,  // 3: atlas.storage.v1.Subsystem.namespaces:type_name -> atlas.storage.v1.Namespace
	3,  // 4: atlas.storage.v1.Device.namespace:type_name -> atlas.storage.v1.Namespace
	4,  // 5: atlas.storage.v1.Device.subsystem:type_name -> atlas.storage.v1.Subsystem
	4,  // 6: atlas.storage.v1.ListSubsystemsResponse.subsystems:type_name -> atlas.storage.v1.Subsystem
	4,  // 7: atlas.storage.v1.GetSubsystemByNQNResponse.subsystem:type_name -> atlas.storage.v1.Subsystem
	5,  // 8: atlas.storage.v1.ListDevicesResponse.devices:type_name -> atlas.storage.v1.Device
	6,  // 9: atlas.storage.v1.ListDevicesBySelectorRequest.selector:type_name -> atlas.storage.v1.DeviceSelector
	5,  // 10: atlas.storage.v1.ListDevicesBySelectorResponse.devices:type_name -> atlas.storage.v1.Device
	5,  // 11: atlas.storage.v1.GetDeviceByUUIDResponse.device:type_name -> atlas.storage.v1.Device
	5,  // 12: atlas.storage.v1.GetDeviceByDevicePathResponse.device:type_name -> atlas.storage.v1.Device
	5,  // 13: atlas.storage.v1.GetDeviceByNamespaceResponse.device:type_name -> atlas.storage.v1.Device
	7,  // 14: atlas.storage.v1.SubsystemService.ListSubsystems:input_type -> atlas.storage.v1.ListSubsystemsRequest
	9,  // 15: atlas.storage.v1.SubsystemService.GetSubsystemByNQN:input_type -> atlas.storage.v1.GetSubsystemByNQNRequest
	11, // 16: atlas.storage.v1.DeviceService.ListDevices:input_type -> atlas.storage.v1.ListDevicesRequest
	13, // 17: atlas.storage.v1.DeviceService.ListDevicesBySelector:input_type -> atlas.storage.v1.ListDevicesBySelectorRequest
	15, // 18: atlas.storage.v1.DeviceService.GetDeviceByUUID:input_type -> atlas.storage.v1.GetDeviceByUUIDRequest
	17, // 19: atlas.storage.v1.DeviceService.GetDeviceByDevicePath:input_type -> atlas.storage.v1.GetDeviceByDevicePathRequest
	19, // 20: atlas.storage.v1.DeviceService.GetDeviceByNamespace:input_type -> atlas.storage.v1.GetDeviceByNamespaceRequest
	8,  // 21: atlas.storage.v1.SubsystemService.ListSubsystems:output_type -> atlas.storage.v1.ListSubsystemsResponse
	10, // 22: atlas.storage.v1.SubsystemService.GetSubsystemByNQN:output_type -> atlas.storage.v1.GetSubsystemByNQNResponse
	12, // 23: atlas.storage.v1.DeviceService.ListDevices:output_type -> atlas.storage.v1.ListDevicesResponse
	14, // 24: atlas.storage.v1.DeviceService.ListDevicesBySelector:output_type -> atlas.storage.v1.ListDevicesBySelectorResponse
	16, // 25: atlas.storage.v1.DeviceService.GetDeviceByUUID:output_type -> atlas.storage.v1.GetDeviceByUUIDResponse
	18, // 26: atlas.storage.v1.DeviceService.GetDeviceByDevicePath:output_type -> atlas.storage.v1.GetDeviceByDevicePathResponse
	20, // 27: atlas.storage.v1.DeviceService.GetDeviceByNamespace:output_type -> atlas.storage.v1.GetDeviceByNamespaceResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_nvme_proto_init() }
func file_nvme_proto_init() {
	if File_nvme_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nvme_proto_rawDesc), len(file_nvme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_nvme_proto_goTypes,
		DependencyIndexes: file_nvme_proto_depIdxs,
		MessageInfos:      file_nvme_proto_msgTypes,
	}.Build()
	File_nvme_proto = out.File
	file_nvme_proto_goTypes = nil
	file_nvme_proto_depIdxs = nil
}
