// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nvme.proto

// Package atlas.storage.v1 exposes a node's local NVMe state to the operator over
// a link.
//
// The messages mirror the snapshot types in the atlas nvme package field for
// field. That is deliberate and worth preserving: those types are immutable
// scans of sysfs with no behaviour attached, so the wire form can be a complete
// copy rather than a summary, and a caller on the far side of a link gets the
// same answers -- including the derived ones like Device.Accessible, which is a
// pure function of the fields carried here -- as a caller on the node.
//
// Everything here is read-only. Attaching and detaching fabrics is a separate,
// mutating service, so that a credential can be granted this and not that.

package storagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SubsystemService_ListSubsystems_FullMethodName    = "/atlas.storage.v1.SubsystemService/ListSubsystems"
	SubsystemService_GetSubsystemByNQN_FullMethodName = "/atlas.storage.v1.SubsystemService/GetSubsystemByNQN"
)

// SubsystemServiceClient is the client API for SubsystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SubsystemService enumerates and finds NVMe subsystems on the node. It is the
// wire form of atlas nvme.SubsystemResolver.
type SubsystemServiceClient interface {
	// ListSubsystems returns every attached NVMe subsystem.
	ListSubsystems(ctx context.Context, in *ListSubsystemsRequest, opts ...grpc.CallOption) (*ListSubsystemsResponse, error)
	// GetSubsystemByNQN returns one subsystem with all of its controller paths
	// and namespaces. A subsystem that is not attached is NOT_FOUND.
	GetSubsystemByNQN(ctx context.Context, in *GetSubsystemByNQNRequest, opts ...grpc.CallOption) (*GetSubsystemByNQNResponse, error)
}

type subsystemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubsystemServiceClient(cc grpc.ClientConnInterface) SubsystemServiceClient {
	return &subsystemServiceClient{cc}
}

func (c *subsystemServiceClient) ListSubsystems(ctx context.Context, in *ListSubsystemsRequest, opts ...grpc.CallOption) (*ListSubsystemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubsystemsResponse)
	err := c.cc.Invoke(ctx, SubsystemService_ListSubsystems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subsystemServiceClient) GetSubsystemByNQN(ctx context.Context, in *GetSubsystemByNQNRequest, opts ...grpc.CallOption) (*GetSubsystemByNQNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubsystemByNQNResponse)
	err := c.cc.Invoke(ctx, SubsystemService_GetSubsystemByNQN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubsystemServiceServer is the server API for SubsystemService service.
// All implementations must embed UnimplementedSubsystemServiceServer
// for forward compatibility.
//
// SubsystemService enumerates and finds NVMe subsystems on the node. It is the
// wire form of atlas nvme.SubsystemResolver.
type SubsystemServiceServer interface {
	// ListSubsystems returns every attached NVMe subsystem.
	ListSubsystems(context.Context, *ListSubsystemsRequest) (*ListSubsystemsResponse, error)
	// GetSubsystemByNQN returns one subsystem with all of its controller paths
	// and namespaces. A subsystem that is not attached is NOT_FOUND.
	GetSubsystemByNQN(context.Context, *GetSubsystemByNQNRequest) (*GetSubsystemByNQNResponse, error)
	mustEmbedUnimplementedSubsystemServiceServer()
}

// UnimplementedSubsystemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubsystemServiceServer struct{}

func (UnimplementedSubsystemServiceServer) ListSubsystems(context.Context, *ListSubsystemsRequest) (*ListSubsystemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubsystems not implemented")
}
func (UnimplementedSubsystemServiceServer) GetSubsystemByNQN(context.Context, *GetSubsystemByNQNRequest) (*GetSubsystemByNQNResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubsystemByNQN not implemented")
}
func (UnimplementedSubsystemServiceServer) mustEmbedUnimplementedSubsystemServiceServer() {}
func (UnimplementedSubsystemServiceServer) testEmbeddedByValue()                          {}

// UnsafeSubsystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubsystemServiceServer will
// result in compilation errors.
type UnsafeSubsystemServiceServer interface {
	mustEmbedUnimplementedSubsystemServiceServer()
}

func RegisterSubsystemServiceServer(s grpc.ServiceRegistrar, srv SubsystemServiceServer) {
	// If the following call panics, it indicates UnimplementedSubsystemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubsystemService_ServiceDesc, srv)
}

func _SubsystemService_ListSubsystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubsystemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubsystemServiceServer).ListSubsystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubsystemService_ListSubsystems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubsystemServiceServer).ListSubsystems(ctx, req.(*ListSubsystemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubsystemService_GetSubsystemByNQN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubsystemByNQNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubsystemServiceServer).GetSubsystemByNQN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubsystemService_GetSubsystemByNQN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubsystemServiceServer).GetSubsystemByNQN(ctx, req.(*GetSubsystemByNQNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubsystemService_ServiceDesc is the grpc.ServiceDesc for SubsystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubsystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.storage.v1.SubsystemService",
	HandlerType: (*SubsystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSubsystems",
			Handler:    _SubsystemService_ListSubsystems_Handler,
		},
		{
			MethodName: "GetSubsystemByNQN",
			Handler:    _SubsystemService_GetSubsystemByNQN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvme.proto",
}

const (
	DeviceService_ListDevices_FullMethodName           = "/atlas.storage.v1.DeviceService/ListDevices"
	DeviceService_ListDevicesBySelector_FullMethodName = "/atlas.storage.v1.DeviceService/ListDevicesBySelector"
	DeviceService_GetDeviceByUUID_FullMethodName       = "/atlas.storage.v1.DeviceService/GetDeviceByUUID"
	DeviceService_GetDeviceByDevicePath_FullMethodName = "/atlas.storage.v1.DeviceService/GetDeviceByDevicePath"
	DeviceService_GetDeviceByNamespace_FullMethodName  = "/atlas.storage.v1.DeviceService/GetDeviceByNamespace"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeviceService enumerates and finds attachable namespace devices on the node.
// It is the wire form of atlas nvme.DeviceResolver.
type DeviceServiceClient interface {
	// ListDevices returns every attached NVMe device.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// ListDevicesBySelector returns every device matching the selector, in the
	// order ListDevices would. It hands back all matches rather than a winner:
	// a selector satisfied by more than one device (a stale namespace lingering
	// beside a freshly connected one) is something the caller has to see, not
	// something the node should resolve by picking. No match is an empty list,
	// not an error.
	ListDevicesBySelector(ctx context.Context, in *ListDevicesBySelectorRequest, opts ...grpc.CallOption) (*ListDevicesBySelectorResponse, error)
	// GetDeviceByUUID returns the device whose namespace UUID matches
	// (simplyblock: the lvol UUID). NOT_FOUND when nothing matches.
	GetDeviceByUUID(ctx context.Context, in *GetDeviceByUUIDRequest, opts ...grpc.CallOption) (*GetDeviceByUUIDResponse, error)
	// GetDeviceByDevicePath returns the device for a block node such as
	// "/dev/nvme0n1". NOT_FOUND when nothing matches.
	GetDeviceByDevicePath(ctx context.Context, in *GetDeviceByDevicePathRequest, opts ...grpc.CallOption) (*GetDeviceByDevicePathResponse, error)
	// GetDeviceByNamespace returns the device identified by its subsystem NQN
	// and namespace id -- the precise coordinates of one namespace when a
	// subsystem exports several. NOT_FOUND when nothing matches.
	GetDeviceByNamespace(ctx context.Context, in *GetDeviceByNamespaceRequest, opts ...grpc.CallOption) (*GetDeviceByNamespaceResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, DeviceService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) ListDevicesBySelector(ctx context.Context, in *ListDevicesBySelectorRequest, opts ...grpc.CallOption) (*ListDevicesBySelectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesBySelectorResponse)
	err := c.cc.Invoke(ctx, DeviceService_ListDevicesBySelector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) GetDeviceByUUID(ctx context.Context, in *GetDeviceByUUIDRequest, opts ...grpc.CallOption) (*GetDeviceByUUIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceByUUIDResponse)
	err := c.cc.Invoke(ctx, DeviceService_GetDeviceByUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) GetDeviceByDevicePath(ctx context.Context, in *GetDeviceByDevicePathRequest, opts ...grpc.CallOption) (*GetDeviceByDevicePathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceByDevicePathResponse)
	err := c.cc.Invoke(ctx, DeviceService_GetDeviceByDevicePath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) GetDeviceByNamespace(ctx context.Context, in *GetDeviceByNamespaceRequest, opts ...grpc.CallOption) (*GetDeviceByNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceByNamespaceResponse)
	err := c.cc.Invoke(ctx, DeviceService_GetDeviceByNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility.
//
// DeviceService enumerates and finds attachable namespace devices on the node.
// It is the wire form of atlas nvme.DeviceResolver.
type DeviceServiceServer interface {
	// ListDevices returns every attached NVMe device.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// ListDevicesBySelector returns every device matching the selector, in the
	// order ListDevices would. It hands back all matches rather than a winner:
	// a selector satisfied by more than one device (a stale namespace lingering
	// beside a freshly connected one) is something the caller has to see, not
	// something the node should resolve by picking. No match is an empty list,
	// not an error.
	ListDevicesBySelector(context.Context, *ListDevicesBySelectorRequest) (*ListDevicesBySelectorResponse, error)
	// GetDeviceByUUID returns the device whose namespace UUID matches
	// (simplyblock: the lvol UUID). NOT_FOUND when nothing matches.
	GetDeviceByUUID(context.Context, *GetDeviceByUUIDRequest) (*GetDeviceByUUIDResponse, error)
	// GetDeviceByDevicePath returns the device for a block node such as
	// "/dev/nvme0n1". NOT_FOUND when nothing matches.
	GetDeviceByDevicePath(context.Context, *GetDeviceByDevicePathRequest) (*GetDeviceByDevicePathResponse, error)
	// GetDeviceByNamespace returns the device identified by its subsystem NQN
	// and namespace id -- the precise coordinates of one namespace when a
	// subsystem exports several. NOT_FOUND when nothing matches.
	GetDeviceByNamespace(context.Context, *GetDeviceByNamespaceRequest) (*GetDeviceByNamespaceResponse, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDeviceServiceServer) ListDevicesBySelector(context.Context, *ListDevicesBySelectorRequest) (*ListDevicesBySelectorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevicesBySelector not implemented")
}
func (UnimplementedDeviceServiceServer) GetDeviceByUUID(context.Context, *GetDeviceByUUIDRequest) (*GetDeviceByUUIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceByUUID not implemented")
}
func (UnimplementedDeviceServiceServer) GetDeviceByDevicePath(context.Context, *GetDeviceByDevicePathRequest) (*GetDeviceByDevicePathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceByDevicePath not implemented")
}
func (UnimplementedDeviceServiceServer) GetDeviceByNamespace(context.Context, *GetDeviceByNamespaceRequest) (*GetDeviceByNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceByNamespace not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}
func (UnimplementedDeviceServiceServer) testEmbeddedByValue()                       {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	// If the following call panics, it indicates UnimplementedDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_ListDevicesBySelector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesBySelectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ListDevicesBySelector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_ListDevicesBySelector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ListDevicesBySelector(ctx, req.(*ListDevicesBySelectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_GetDeviceByUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceByUUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDeviceByUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetDeviceByUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDeviceByUUID(ctx, req.(*GetDeviceByUUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_GetDeviceByDevicePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceByDevicePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDeviceByDevicePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetDeviceByDevicePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDeviceByDevicePath(ctx, req.(*GetDeviceByDevicePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_GetDeviceByNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceByNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).GetDeviceByNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_GetDeviceByNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).GetDeviceByNamespace(ctx, req.(*GetDeviceByNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.storage.v1.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevices",
			Handler:    _DeviceService_ListDevices_Handler,
		},
		{
			MethodName: "ListDevicesBySelector",
			Handler:    _DeviceService_ListDevicesBySelector_Handler,
		},
		{
			MethodName: "GetDeviceByUUID",
			Handler:    _DeviceService_GetDeviceByUUID_Handler,
		},
		{
			MethodName: "GetDeviceByDevicePath",
			Handler:    _DeviceService_GetDeviceByDevicePath_Handler,
		},
		{
			MethodName: "GetDeviceByNamespace",
			Handler:    _DeviceService_GetDeviceByNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nvme.proto",
}
