//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachedClaim) DeepCopyInto(out *AttachedClaim) {
	*out = *in
	if in.AttachedAt != nil {
		in, out := &in.AttachedAt, &out.AttachedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachedClaim.
func (in *AttachedClaim) DeepCopy() *AttachedClaim {
	if in == nil {
		return nil
	}
	out := new(AttachedClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupCopy) DeepCopyInto(out *BackupCopy) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int64)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupCopy.
func (in *BackupCopy) DeepCopy() *BackupCopy {
	if in == nil {
		return nil
	}
	out := new(BackupCopy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupSource) DeepCopyInto(out *BackupSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupSource.
func (in *BackupSource) DeepCopy() *BackupSource {
	if in == nil {
		return nil
	}
	out := new(BackupSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentConfig) DeepCopyInto(out *ClusterDeploymentConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentConfig.
func (in *ClusterDeploymentConfig) DeepCopy() *ClusterDeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterDeploymentConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentConfigList) DeepCopyInto(out *ClusterDeploymentConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterDeploymentConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentConfigList.
func (in *ClusterDeploymentConfigList) DeepCopy() *ClusterDeploymentConfigList {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterDeploymentConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentConfigSpec) DeepCopyInto(out *ClusterDeploymentConfigSpec) {
	*out = *in
	if in.EdgeCluster != nil {
		in, out := &in.EdgeCluster, &out.EdgeCluster
		*out = new(bool)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ClusterTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSets != nil {
		in, out := &in.NodeSets, &out.NodeSets
		*out = make([]NodeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentConfigSpec.
func (in *ClusterDeploymentConfigSpec) DeepCopy() *ClusterDeploymentConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentConfigStatus) DeepCopyInto(out *ClusterDeploymentConfigStatus) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	if in.NodeRefs != nil {
		in, out := &in.NodeRefs, &out.NodeRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentConfigStatus.
func (in *ClusterDeploymentConfigStatus) DeepCopy() *ClusterDeploymentConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTemplate) DeepCopyInto(out *ClusterTemplate) {
	*out = *in
	if in.MaxSubsystemCount != nil {
		in, out := &in.MaxSubsystemCount, &out.MaxSubsystemCount
		*out = new(int32)
		**out = **in
	}
	if in.VCPUCount != nil {
		in, out := &in.VCPUCount, &out.VCPUCount
		*out = new(int32)
		**out = **in
	}
	if in.Stripe != nil {
		in, out := &in.Stripe, &out.Stripe
		*out = new(StripeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableFailureDomains != nil {
		in, out := &in.EnableFailureDomains, &out.EnableFailureDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTemplate.
func (in *ClusterTemplate) DeepCopy() *ClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlane) DeepCopyInto(out *ControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlane.
func (in *ControlPlane) DeepCopy() *ControlPlane {
	if in == nil {
		return nil
	}
	out := new(ControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneList) DeepCopyInto(out *ControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneList.
func (in *ControlPlaneList) DeepCopy() *ControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneSource) DeepCopyInto(out *ControlPlaneSource) {
	*out = *in
	if in.Managed != nil {
		in, out := &in.Managed, &out.Managed
		*out = new(ManagedControlPlane)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneSource.
func (in *ControlPlaneSource) DeepCopy() *ControlPlaneSource {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneSpec) DeepCopyInto(out *ControlPlaneSpec) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(ControlPlaneSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneSpec.
func (in *ControlPlaneSpec) DeepCopy() *ControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneStatus) DeepCopyInto(out *ControlPlaneStatus) {
	*out = *in
	if in.LastChecked != nil {
		in, out := &in.LastChecked, &out.LastChecked
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneStatus.
func (in *ControlPlaneStatus) DeepCopy() *ControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceCapacity) DeepCopyInto(out *DeviceCapacity) {
	*out = *in
	if in.TotalBytes != nil {
		in, out := &in.TotalBytes, &out.TotalBytes
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceCapacity.
func (in *DeviceCapacity) DeepCopy() *DeviceCapacity {
	if in == nil {
		return nil
	}
	out := new(DeviceCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceFilter) DeepCopyInto(out *DeviceFilter) {
	*out = *in
	if in.EnableLogicalBlockDevices != nil {
		in, out := &in.EnableLogicalBlockDevices, &out.EnableLogicalBlockDevices
		*out = new(bool)
		**out = **in
	}
	if in.EnablePartitionedDevices != nil {
		in, out := &in.EnablePartitionedDevices, &out.EnablePartitionedDevices
		*out = new(bool)
		**out = **in
	}
	if in.PcieAllowList != nil {
		in, out := &in.PcieAllowList, &out.PcieAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PcieDenyList != nil {
		in, out := &in.PcieDenyList, &out.PcieDenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockAllowList != nil {
		in, out := &in.BlockAllowList, &out.BlockAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockDenyList != nil {
		in, out := &in.BlockDenyList, &out.BlockDenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceFilter.
func (in *DeviceFilter) DeepCopy() *DeviceFilter {
	if in == nil {
		return nil
	}
	out := new(DeviceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceHardware) DeepCopyInto(out *DeviceHardware) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceHardware.
func (in *DeviceHardware) DeepCopy() *DeviceHardware {
	if in == nil {
		return nil
	}
	out := new(DeviceHardware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSelection) DeepCopyInto(out *DeviceSelection) {
	*out = *in
	if in.NVMe != nil {
		in, out := &in.NVMe, &out.NVMe
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSelection.
func (in *DeviceSelection) DeepCopy() *DeviceSelection {
	if in == nil {
		return nil
	}
	out := new(DeviceSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverSpec) DeepCopyInto(out *DiscoverSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeviceFilter != nil {
		in, out := &in.DeviceFilter, &out.DeviceFilter
		*out = new(DeviceFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverSpec.
func (in *DiscoverSpec) DeepCopy() *DiscoverSpec {
	if in == nil {
		return nil
	}
	out := new(DiscoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverTLS) DeepCopyInto(out *DriverTLS) {
	*out = *in
	if in.EnableTLS != nil {
		in, out := &in.EnableTLS, &out.EnableTLS
		*out = new(bool)
		**out = **in
	}
	if in.EnableMutualTLS != nil {
		in, out := &in.EnableMutualTLS, &out.EnableMutualTLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverTLS.
func (in *DriverTLS) DeepCopy() *DriverTLS {
	if in == nil {
		return nil
	}
	out := new(DriverTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JournalManagerSpec) DeepCopyInto(out *JournalManagerSpec) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int32)
		**out = **in
	}
	if in.PercentPerDevice != nil {
		in, out := &in.PercentPerDevice, &out.PercentPerDevice
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JournalManagerSpec.
func (in *JournalManagerSpec) DeepCopy() *JournalManagerSpec {
	if in == nil {
		return nil
	}
	out := new(JournalManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedControlPlane) DeepCopyInto(out *ManagedControlPlane) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedControlPlane.
func (in *ManagedControlPlane) DeepCopy() *ManagedControlPlane {
	if in == nil {
		return nil
	}
	out := new(ManagedControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrateSpec) DeepCopyInto(out *MigrateSpec) {
	*out = *in
	if in.NewSsdPcie != nil {
		in, out := &in.NewSsdPcie, &out.NewSsdPcie
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrateSpec.
func (in *MigrateSpec) DeepCopy() *MigrateSpec {
	if in == nil {
		return nil
	}
	out := new(MigrateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroup) DeepCopyInto(out *NodeGroup) {
	*out = *in
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataInterfaces != nil {
		in, out := &in.DataInterfaces, &out.DataInterfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = new(DeviceSelection)
		(*in).DeepCopyInto(*out)
	}
	if in.JournalManager != nil {
		in, out := &in.JournalManager, &out.JournalManager
		*out = new(JournalManagerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroup.
func (in *NodeGroup) DeepCopy() *NodeGroup {
	if in == nil {
		return nil
	}
	out := new(NodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSet) DeepCopyInto(out *NodeSet) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]NodeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSet.
func (in *NodeSet) DeepCopy() *NodeSet {
	if in == nil {
		return nil
	}
	out := new(NodeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorOps) DeepCopyInto(out *OperatorOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorOps.
func (in *OperatorOps) DeepCopy() *OperatorOps {
	if in == nil {
		return nil
	}
	out := new(OperatorOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorOpsList) DeepCopyInto(out *OperatorOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperatorOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorOpsList.
func (in *OperatorOpsList) DeepCopy() *OperatorOpsList {
	if in == nil {
		return nil
	}
	out := new(OperatorOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorOpsSpec) DeepCopyInto(out *OperatorOpsSpec) {
	*out = *in
	if in.Discover != nil {
		in, out := &in.Discover, &out.Discover
		*out = new(DiscoverSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorOpsSpec.
func (in *OperatorOpsSpec) DeepCopy() *OperatorOpsSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorOpsStatus) DeepCopyInto(out *OperatorOpsStatus) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorOpsStatus.
func (in *OperatorOpsStatus) DeepCopy() *OperatorOpsStatus {
	if in == nil {
		return nil
	}
	out := new(OperatorOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolLimits) DeepCopyInto(out *PoolLimits) {
	*out = *in
	if in.IOPS != nil {
		in, out := &in.IOPS, &out.IOPS
		*out = new(int32)
		**out = **in
	}
	if in.Throughput != nil {
		in, out := &in.Throughput, &out.Throughput
		*out = new(ThroughputLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolLimits.
func (in *PoolLimits) DeepCopy() *PoolLimits {
	if in == nil {
		return nil
	}
	out := new(PoolLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolLimitsStatus) DeepCopyInto(out *PoolLimitsStatus) {
	*out = *in
	if in.IOPS != nil {
		in, out := &in.IOPS, &out.IOPS
		*out = new(int32)
		**out = **in
	}
	if in.Throughput != nil {
		in, out := &in.Throughput, &out.Throughput
		*out = new(ThroughputLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolLimitsStatus.
func (in *PoolLimitsStatus) DeepCopy() *PoolLimitsStatus {
	if in == nil {
		return nil
	}
	out := new(PoolLimitsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoveSpec) DeepCopyInto(out *RemoveSpec) {
	*out = *in
	if in.SystemVolumeFilterRegex != nil {
		in, out := &in.SystemVolumeFilterRegex, &out.SystemVolumeFilterRegex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoveSpec.
func (in *RemoveSpec) DeepCopy() *RemoveSpec {
	if in == nil {
		return nil
	}
	out := new(RemoveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSpec) DeepCopyInto(out *RestoreSpec) {
	*out = *in
	if in.ClaimLabels != nil {
		in, out := &in.ClaimLabels, &out.ClaimLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClaimAnnotations != nil {
		in, out := &in.ClaimAnnotations, &out.ClaimAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSpec.
func (in *RestoreSpec) DeepCopy() *RestoreSpec {
	if in == nil {
		return nil
	}
	out := new(RestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingRestartSpec) DeepCopyInto(out *RollingRestartSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingRestartSpec.
func (in *RollingRestartSpec) DeepCopy() *RollingRestartSpec {
	if in == nil {
		return nil
	}
	out := new(RollingRestartSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingRestartStatus) DeepCopyInto(out *RollingRestartStatus) {
	*out = *in
	if in.PendingNodes != nil {
		in, out := &in.PendingNodes, &out.PendingNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcessedNodes != nil {
		in, out := &in.ProcessedNodes, &out.ProcessedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingRestartStatus.
func (in *RollingRestartStatus) DeepCopy() *RollingRestartStatus {
	if in == nil {
		return nil
	}
	out := new(RollingRestartStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarImages) DeepCopyInto(out *SidecarImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarImages.
func (in *SidecarImages) DeepCopy() *SidecarImages {
	if in == nil {
		return nil
	}
	out := new(SidecarImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyblockDriver) DeepCopyInto(out *SimplyblockDriver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyblockDriver.
func (in *SimplyblockDriver) DeepCopy() *SimplyblockDriver {
	if in == nil {
		return nil
	}
	out := new(SimplyblockDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimplyblockDriver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyblockDriverList) DeepCopyInto(out *SimplyblockDriverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SimplyblockDriver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyblockDriverList.
func (in *SimplyblockDriverList) DeepCopy() *SimplyblockDriverList {
	if in == nil {
		return nil
	}
	out := new(SimplyblockDriverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimplyblockDriverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyblockDriverSpec) DeepCopyInto(out *SimplyblockDriverSpec) {
	*out = *in
	if in.ControllerReplicas != nil {
		in, out := &in.ControllerReplicas, &out.ControllerReplicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ControllerNodeSelector != nil {
		in, out := &in.ControllerNodeSelector, &out.ControllerNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ControllerTolerations != nil {
		in, out := &in.ControllerTolerations, &out.ControllerTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ControllerResources.DeepCopyInto(&out.ControllerResources)
	in.NodeResources.DeepCopyInto(&out.NodeResources)
	out.SidecarImages = in.SidecarImages
	if in.EnableServiceAccountAuth != nil {
		in, out := &in.EnableServiceAccountAuth, &out.EnableServiceAccountAuth
		*out = new(bool)
		**out = **in
	}
	if in.EnableVolumeSnapshots != nil {
		in, out := &in.EnableVolumeSnapshots, &out.EnableVolumeSnapshots
		*out = new(bool)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyblockDriverSpec.
func (in *SimplyblockDriverSpec) DeepCopy() *SimplyblockDriverSpec {
	if in == nil {
		return nil
	}
	out := new(SimplyblockDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyblockDriverStatus) DeepCopyInto(out *SimplyblockDriverStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyblockDriverStatus.
func (in *SimplyblockDriverStatus) DeepCopy() *SimplyblockDriverStatus {
	if in == nil {
		return nil
	}
	out := new(SimplyblockDriverStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackup) DeepCopyInto(out *StorageBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackup.
func (in *StorageBackup) DeepCopy() *StorageBackup {
	if in == nil {
		return nil
	}
	out := new(StorageBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupList) DeepCopyInto(out *StorageBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupList.
func (in *StorageBackupList) DeepCopy() *StorageBackupList {
	if in == nil {
		return nil
	}
	out := new(StorageBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupOps) DeepCopyInto(out *StorageBackupOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupOps.
func (in *StorageBackupOps) DeepCopy() *StorageBackupOps {
	if in == nil {
		return nil
	}
	out := new(StorageBackupOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackupOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupOpsList) DeepCopyInto(out *StorageBackupOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBackupOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupOpsList.
func (in *StorageBackupOpsList) DeepCopy() *StorageBackupOpsList {
	if in == nil {
		return nil
	}
	out := new(StorageBackupOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackupOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupOpsSpec) DeepCopyInto(out *StorageBackupOpsSpec) {
	*out = *in
	if in.Restore != nil {
		in, out := &in.Restore, &out.Restore
		*out = new(RestoreSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupOpsSpec.
func (in *StorageBackupOpsSpec) DeepCopy() *StorageBackupOpsSpec {
	if in == nil {
		return nil
	}
	out := new(StorageBackupOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupOpsStatus) DeepCopyInto(out *StorageBackupOpsStatus) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupOpsStatus.
func (in *StorageBackupOpsStatus) DeepCopy() *StorageBackupOpsStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBackupOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupPolicy) DeepCopyInto(out *StorageBackupPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupPolicy.
func (in *StorageBackupPolicy) DeepCopy() *StorageBackupPolicy {
	if in == nil {
		return nil
	}
	out := new(StorageBackupPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackupPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupPolicyList) DeepCopyInto(out *StorageBackupPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageBackupPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupPolicyList.
func (in *StorageBackupPolicyList) DeepCopy() *StorageBackupPolicyList {
	if in == nil {
		return nil
	}
	out := new(StorageBackupPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageBackupPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupPolicySpec) DeepCopyInto(out *StorageBackupPolicySpec) {
	*out = *in
	if in.ClaimSelector != nil {
		in, out := &in.ClaimSelector, &out.ClaimSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxVersions != nil {
		in, out := &in.MaxVersions, &out.MaxVersions
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupPolicySpec.
func (in *StorageBackupPolicySpec) DeepCopy() *StorageBackupPolicySpec {
	if in == nil {
		return nil
	}
	out := new(StorageBackupPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupPolicyStatus) DeepCopyInto(out *StorageBackupPolicyStatus) {
	*out = *in
	if in.AttachedClaims != nil {
		in, out := &in.AttachedClaims, &out.AttachedClaims
		*out = make([]AttachedClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastBackupAt != nil {
		in, out := &in.LastBackupAt, &out.LastBackupAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupPolicyStatus.
func (in *StorageBackupPolicyStatus) DeepCopy() *StorageBackupPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBackupPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupSpec) DeepCopyInto(out *StorageBackupSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupSpec.
func (in *StorageBackupSpec) DeepCopy() *StorageBackupSpec {
	if in == nil {
		return nil
	}
	out := new(StorageBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageBackupStatus) DeepCopyInto(out *StorageBackupStatus) {
	*out = *in
	if in.Backup != nil {
		in, out := &in.Backup, &out.Backup
		*out = new(BackupCopy)
		(*in).DeepCopyInto(*out)
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(BackupSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageBackupStatus.
func (in *StorageBackupStatus) DeepCopy() *StorageBackupStatus {
	if in == nil {
		return nil
	}
	out := new(StorageBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClusterOps) DeepCopyInto(out *StorageClusterOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClusterOps.
func (in *StorageClusterOps) DeepCopy() *StorageClusterOps {
	if in == nil {
		return nil
	}
	out := new(StorageClusterOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageClusterOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClusterOpsList) DeepCopyInto(out *StorageClusterOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageClusterOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClusterOpsList.
func (in *StorageClusterOpsList) DeepCopy() *StorageClusterOpsList {
	if in == nil {
		return nil
	}
	out := new(StorageClusterOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageClusterOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClusterOpsSpec) DeepCopyInto(out *StorageClusterOpsSpec) {
	*out = *in
	if in.RollingRestart != nil {
		in, out := &in.RollingRestart, &out.RollingRestart
		*out = new(RollingRestartSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClusterOpsSpec.
func (in *StorageClusterOpsSpec) DeepCopy() *StorageClusterOpsSpec {
	if in == nil {
		return nil
	}
	out := new(StorageClusterOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClusterOpsStatus) DeepCopyInto(out *StorageClusterOpsStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.RollingRestart != nil {
		in, out := &in.RollingRestart, &out.RollingRestart
		*out = new(RollingRestartStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClusterOpsStatus.
func (in *StorageClusterOpsStatus) DeepCopy() *StorageClusterOpsStatus {
	if in == nil {
		return nil
	}
	out := new(StorageClusterOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDevice) DeepCopyInto(out *StorageDevice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDevice.
func (in *StorageDevice) DeepCopy() *StorageDevice {
	if in == nil {
		return nil
	}
	out := new(StorageDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageDevice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDeviceList) DeepCopyInto(out *StorageDeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDeviceList.
func (in *StorageDeviceList) DeepCopy() *StorageDeviceList {
	if in == nil {
		return nil
	}
	out := new(StorageDeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageDeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDeviceSpec) DeepCopyInto(out *StorageDeviceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDeviceSpec.
func (in *StorageDeviceSpec) DeepCopy() *StorageDeviceSpec {
	if in == nil {
		return nil
	}
	out := new(StorageDeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDeviceStatus) DeepCopyInto(out *StorageDeviceStatus) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(DeviceCapacity)
		(*in).DeepCopyInto(*out)
	}
	if in.Hardware != nil {
		in, out := &in.Hardware, &out.Hardware
		*out = new(DeviceHardware)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDeviceStatus.
func (in *StorageDeviceStatus) DeepCopy() *StorageDeviceStatus {
	if in == nil {
		return nil
	}
	out := new(StorageDeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageNodeOps) DeepCopyInto(out *StorageNodeOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageNodeOps.
func (in *StorageNodeOps) DeepCopy() *StorageNodeOps {
	if in == nil {
		return nil
	}
	out := new(StorageNodeOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageNodeOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageNodeOpsList) DeepCopyInto(out *StorageNodeOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageNodeOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageNodeOpsList.
func (in *StorageNodeOpsList) DeepCopy() *StorageNodeOpsList {
	if in == nil {
		return nil
	}
	out := new(StorageNodeOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageNodeOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageNodeOpsSpec) DeepCopyInto(out *StorageNodeOpsSpec) {
	*out = *in
	if in.Force != nil {
		in, out := &in.Force, &out.Force
		*out = new(bool)
		**out = **in
	}
	if in.ReattachVolume != nil {
		in, out := &in.ReattachVolume, &out.ReattachVolume
		*out = new(bool)
		**out = **in
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = new(MigrateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Remove != nil {
		in, out := &in.Remove, &out.Remove
		*out = new(RemoveSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageNodeOpsSpec.
func (in *StorageNodeOpsSpec) DeepCopy() *StorageNodeOpsSpec {
	if in == nil {
		return nil
	}
	out := new(StorageNodeOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageNodeOpsStatus) DeepCopyInto(out *StorageNodeOpsStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageNodeOpsStatus.
func (in *StorageNodeOpsStatus) DeepCopy() *StorageNodeOpsStatus {
	if in == nil {
		return nil
	}
	out := new(StorageNodeOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePool) DeepCopyInto(out *StoragePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePool.
func (in *StoragePool) DeepCopy() *StoragePool {
	if in == nil {
		return nil
	}
	out := new(StoragePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolList) DeepCopyInto(out *StoragePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StoragePool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolList.
func (in *StoragePoolList) DeepCopy() *StoragePoolList {
	if in == nil {
		return nil
	}
	out := new(StoragePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolOps) DeepCopyInto(out *StoragePoolOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolOps.
func (in *StoragePoolOps) DeepCopy() *StoragePoolOps {
	if in == nil {
		return nil
	}
	out := new(StoragePoolOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePoolOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolOpsList) DeepCopyInto(out *StoragePoolOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StoragePoolOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolOpsList.
func (in *StoragePoolOpsList) DeepCopy() *StoragePoolOpsList {
	if in == nil {
		return nil
	}
	out := new(StoragePoolOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePoolOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolOpsSpec) DeepCopyInto(out *StoragePoolOpsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolOpsSpec.
func (in *StoragePoolOpsSpec) DeepCopy() *StoragePoolOpsSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePoolOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolOpsStatus) DeepCopyInto(out *StoragePoolOpsStatus) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolOpsStatus.
func (in *StoragePoolOpsStatus) DeepCopy() *StoragePoolOpsStatus {
	if in == nil {
		return nil
	}
	out := new(StoragePoolOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolSpec) DeepCopyInto(out *StoragePoolSpec) {
	*out = *in
	if in.AllowedNodes != nil {
		in, out := &in.AllowedNodes, &out.AllowedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(PoolLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeDefaults != nil {
		in, out := &in.VolumeDefaults, &out.VolumeDefaults
		*out = new(VolumeDefaults)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolSpec.
func (in *StoragePoolSpec) DeepCopy() *StoragePoolSpec {
	if in == nil {
		return nil
	}
	out := new(StoragePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolStatus) DeepCopyInto(out *StoragePoolStatus) {
	*out = *in
	if in.StorageClassNames != nil {
		in, out := &in.StorageClassNames, &out.StorageClassNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(PoolLimitsStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowedNodes != nil {
		in, out := &in.AllowedNodes, &out.AllowedNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolStatus.
func (in *StoragePoolStatus) DeepCopy() *StoragePoolStatus {
	if in == nil {
		return nil
	}
	out := new(StoragePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StripeSpec) DeepCopyInto(out *StripeSpec) {
	*out = *in
	if in.DataChunks != nil {
		in, out := &in.DataChunks, &out.DataChunks
		*out = new(int32)
		**out = **in
	}
	if in.ParityChunks != nil {
		in, out := &in.ParityChunks, &out.ParityChunks
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StripeSpec.
func (in *StripeSpec) DeepCopy() *StripeSpec {
	if in == nil {
		return nil
	}
	out := new(StripeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThroughputLimits) DeepCopyInto(out *ThroughputLimits) {
	*out = *in
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(int32)
		**out = **in
	}
	if in.Write != nil {
		in, out := &in.Write, &out.Write
		*out = new(int32)
		**out = **in
	}
	if in.ReadWrite != nil {
		in, out := &in.ReadWrite, &out.ReadWrite
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThroughputLimits.
func (in *ThroughputLimits) DeepCopy() *ThroughputLimits {
	if in == nil {
		return nil
	}
	out := new(ThroughputLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeDefaults) DeepCopyInto(out *VolumeDefaults) {
	*out = *in
	if in.IOPS != nil {
		in, out := &in.IOPS, &out.IOPS
		*out = new(int32)
		**out = **in
	}
	if in.Throughput != nil {
		in, out := &in.Throughput, &out.Throughput
		*out = new(ThroughputLimits)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableCompression != nil {
		in, out := &in.EnableCompression, &out.EnableCompression
		*out = new(bool)
		**out = **in
	}
	if in.EnableEncryption != nil {
		in, out := &in.EnableEncryption, &out.EnableEncryption
		*out = new(bool)
		**out = **in
	}
	if in.EnableReplication != nil {
		in, out := &in.EnableReplication, &out.EnableReplication
		*out = new(bool)
		**out = **in
	}
	if in.EnableDHCHAP != nil {
		in, out := &in.EnableDHCHAP, &out.EnableDHCHAP
		*out = new(bool)
		**out = **in
	}
	if in.MaxNamespacesPerSubsystem != nil {
		in, out := &in.MaxNamespacesPerSubsystem, &out.MaxNamespacesPerSubsystem
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeDefaults.
func (in *VolumeDefaults) DeepCopy() *VolumeDefaults {
	if in == nil {
		return nil
	}
	out := new(VolumeDefaults)
	in.DeepCopyInto(out)
	return out
}
