//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/simplyblock/simplyblock-operator/api/v1alpha1"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentConfig) DeepCopyInto(out *ClusterDeploymentConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentConfig.
func (in *ClusterDeploymentConfig) DeepCopy() *ClusterDeploymentConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterDeploymentConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentConfigList) DeepCopyInto(out *ClusterDeploymentConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterDeploymentConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentConfigList.
func (in *ClusterDeploymentConfigList) DeepCopy() *ClusterDeploymentConfigList {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterDeploymentConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentConfigSpec) DeepCopyInto(out *ClusterDeploymentConfigSpec) {
	*out = *in
	if in.EdgeCluster != nil {
		in, out := &in.EdgeCluster, &out.EdgeCluster
		*out = new(bool)
		**out = **in
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(ClusterTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSets != nil {
		in, out := &in.NodeSets, &out.NodeSets
		*out = make([]NodeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentConfigSpec.
func (in *ClusterDeploymentConfigSpec) DeepCopy() *ClusterDeploymentConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterDeploymentConfigStatus) DeepCopyInto(out *ClusterDeploymentConfigStatus) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	if in.NodeRefs != nil {
		in, out := &in.NodeRefs, &out.NodeRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterDeploymentConfigStatus.
func (in *ClusterDeploymentConfigStatus) DeepCopy() *ClusterDeploymentConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterDeploymentConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTemplate) DeepCopyInto(out *ClusterTemplate) {
	*out = *in
	if in.MaxSubsystemCount != nil {
		in, out := &in.MaxSubsystemCount, &out.MaxSubsystemCount
		*out = new(int32)
		**out = **in
	}
	if in.VCPUCount != nil {
		in, out := &in.VCPUCount, &out.VCPUCount
		*out = new(int32)
		**out = **in
	}
	if in.Stripe != nil {
		in, out := &in.Stripe, &out.Stripe
		*out = new(v1alpha1.StripeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableFailureDomains != nil {
		in, out := &in.EnableFailureDomains, &out.EnableFailureDomains
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTemplate.
func (in *ClusterTemplate) DeepCopy() *ClusterTemplate {
	if in == nil {
		return nil
	}
	out := new(ClusterTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceFilter) DeepCopyInto(out *DeviceFilter) {
	*out = *in
	if in.EnableLogicalBlockDevices != nil {
		in, out := &in.EnableLogicalBlockDevices, &out.EnableLogicalBlockDevices
		*out = new(bool)
		**out = **in
	}
	if in.EnablePartitionedDevices != nil {
		in, out := &in.EnablePartitionedDevices, &out.EnablePartitionedDevices
		*out = new(bool)
		**out = **in
	}
	if in.PcieAllowList != nil {
		in, out := &in.PcieAllowList, &out.PcieAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PcieDenyList != nil {
		in, out := &in.PcieDenyList, &out.PcieDenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockAllowList != nil {
		in, out := &in.BlockAllowList, &out.BlockAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockDenyList != nil {
		in, out := &in.BlockDenyList, &out.BlockDenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceFilter.
func (in *DeviceFilter) DeepCopy() *DeviceFilter {
	if in == nil {
		return nil
	}
	out := new(DeviceFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSelection) DeepCopyInto(out *DeviceSelection) {
	*out = *in
	if in.NVMe != nil {
		in, out := &in.NVMe, &out.NVMe
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSelection.
func (in *DeviceSelection) DeepCopy() *DeviceSelection {
	if in == nil {
		return nil
	}
	out := new(DeviceSelection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoverSpec) DeepCopyInto(out *DiscoverSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DeviceFilter != nil {
		in, out := &in.DeviceFilter, &out.DeviceFilter
		*out = new(DeviceFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoverSpec.
func (in *DiscoverSpec) DeepCopy() *DiscoverSpec {
	if in == nil {
		return nil
	}
	out := new(DiscoverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriverTLS) DeepCopyInto(out *DriverTLS) {
	*out = *in
	if in.EnableTLS != nil {
		in, out := &in.EnableTLS, &out.EnableTLS
		*out = new(bool)
		**out = **in
	}
	if in.EnableMutualTLS != nil {
		in, out := &in.EnableMutualTLS, &out.EnableMutualTLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriverTLS.
func (in *DriverTLS) DeepCopy() *DriverTLS {
	if in == nil {
		return nil
	}
	out := new(DriverTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeGroup) DeepCopyInto(out *NodeGroup) {
	*out = *in
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataInterfaces != nil {
		in, out := &in.DataInterfaces, &out.DataInterfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = new(DeviceSelection)
		(*in).DeepCopyInto(*out)
	}
	if in.JournalManager != nil {
		in, out := &in.JournalManager, &out.JournalManager
		*out = new(v1alpha1.JournalManagerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeGroup.
func (in *NodeGroup) DeepCopy() *NodeGroup {
	if in == nil {
		return nil
	}
	out := new(NodeGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSet) DeepCopyInto(out *NodeSet) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]NodeGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSet.
func (in *NodeSet) DeepCopy() *NodeSet {
	if in == nil {
		return nil
	}
	out := new(NodeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorOps) DeepCopyInto(out *OperatorOps) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorOps.
func (in *OperatorOps) DeepCopy() *OperatorOps {
	if in == nil {
		return nil
	}
	out := new(OperatorOps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorOps) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorOpsList) DeepCopyInto(out *OperatorOpsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OperatorOps, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorOpsList.
func (in *OperatorOpsList) DeepCopy() *OperatorOpsList {
	if in == nil {
		return nil
	}
	out := new(OperatorOpsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OperatorOpsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorOpsSpec) DeepCopyInto(out *OperatorOpsSpec) {
	*out = *in
	if in.Discover != nil {
		in, out := &in.Discover, &out.Discover
		*out = new(DiscoverSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorOpsSpec.
func (in *OperatorOpsSpec) DeepCopy() *OperatorOpsSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorOpsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorOpsStatus) DeepCopyInto(out *OperatorOpsStatus) {
	*out = *in
	in.Step.DeepCopyInto(&out.Step)
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorOpsStatus.
func (in *OperatorOpsStatus) DeepCopy() *OperatorOpsStatus {
	if in == nil {
		return nil
	}
	out := new(OperatorOpsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarImages) DeepCopyInto(out *SidecarImages) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarImages.
func (in *SidecarImages) DeepCopy() *SidecarImages {
	if in == nil {
		return nil
	}
	out := new(SidecarImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyblockDriver) DeepCopyInto(out *SimplyblockDriver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyblockDriver.
func (in *SimplyblockDriver) DeepCopy() *SimplyblockDriver {
	if in == nil {
		return nil
	}
	out := new(SimplyblockDriver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimplyblockDriver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyblockDriverList) DeepCopyInto(out *SimplyblockDriverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SimplyblockDriver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyblockDriverList.
func (in *SimplyblockDriverList) DeepCopy() *SimplyblockDriverList {
	if in == nil {
		return nil
	}
	out := new(SimplyblockDriverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimplyblockDriverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyblockDriverSpec) DeepCopyInto(out *SimplyblockDriverSpec) {
	*out = *in
	if in.ControllerReplicas != nil {
		in, out := &in.ControllerReplicas, &out.ControllerReplicas
		*out = new(int32)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ControllerNodeSelector != nil {
		in, out := &in.ControllerNodeSelector, &out.ControllerNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ControllerTolerations != nil {
		in, out := &in.ControllerTolerations, &out.ControllerTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ControllerResources.DeepCopyInto(&out.ControllerResources)
	in.NodeResources.DeepCopyInto(&out.NodeResources)
	out.SidecarImages = in.SidecarImages
	if in.EnableServiceAccountAuth != nil {
		in, out := &in.EnableServiceAccountAuth, &out.EnableServiceAccountAuth
		*out = new(bool)
		**out = **in
	}
	if in.EnableVolumeSnapshots != nil {
		in, out := &in.EnableVolumeSnapshots, &out.EnableVolumeSnapshots
		*out = new(bool)
		**out = **in
	}
	in.TLS.DeepCopyInto(&out.TLS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyblockDriverSpec.
func (in *SimplyblockDriverSpec) DeepCopy() *SimplyblockDriverSpec {
	if in == nil {
		return nil
	}
	out := new(SimplyblockDriverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyblockDriverStatus) DeepCopyInto(out *SimplyblockDriverStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyblockDriverStatus.
func (in *SimplyblockDriverStatus) DeepCopy() *SimplyblockDriverStatus {
	if in == nil {
		return nil
	}
	out := new(SimplyblockDriverStatus)
	in.DeepCopyInto(out)
	return out
}
