---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplyblock-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resourceNames:
  - controlplanes.storage.simplyblock.io
  - storagebackups.storage.simplyblock.io
  - storageclusterops.storage.simplyblock.io
  - storagenodeops.storage.simplyblock.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - storage.simplyblock.io
  resources:
  - backupimports
  - backuppolicies
  - backuprestores
  - controlplanes
  - operatorops
  - replicationops
  - replicationpairs
  - replicationpolicies
  - replicationslots
  - simplyblockdrivers
  - storagebackupops
  - storagebackuppolicies
  - storagebackups
  - storageclusterops
  - storageclusters
  - storagedevices
  - storagenodeops
  - storagenodes
  - storagenodesets
  - storagepools
  - tasks
  - volumemigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.simplyblock.io
  resources:
  - backupimports/finalizers
  - backuppolicies/finalizers
  - backuprestores/finalizers
  - operatorops/finalizers
  - replicationops/finalizers
  - replicationpairs/finalizers
  - replicationpolicies/finalizers
  - replicationslots/finalizers
  - simplyblockdrivers/finalizers
  - storagebackupops/finalizers
  - storagebackuppolicies/finalizers
  - storageclusterops/finalizers
  - storageclusters/finalizers
  - storagenodeops/finalizers
  - storagenodes/finalizers
  - storagenodesets/finalizers
  - storagepools/finalizers
  - tasks/finalizers
  - volumemigrations/finalizers
  verbs:
  - update
- apiGroups:
  - storage.simplyblock.io
  resources:
  - backupimports/status
  - backuppolicies/status
  - backuprestores/status
  - clusterdeploymentconfigs/status
  - controlplanes/status
  - operatorops/status
  - replicationops/status
  - replicationpairs/status
  - replicationpolicies/status
  - replicationslots/status
  - simplyblockdrivers/status
  - storagebackupops/status
  - storagebackuppolicies/status
  - storagebackups/status
  - storageclusterops/status
  - storageclusters/status
  - storagedevices/status
  - storagenodeops/status
  - storagenodes/status
  - storagenodesets/status
  - storagepools/status
  - tasks/status
  - volumemigrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.simplyblock.io
  resources:
  - clusterdeploymentconfigs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
