//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogicalVolumeCapacity) DeepCopyInto(out *LogicalVolumeCapacity) {
	*out = *in
	out.Provisioned = in.Provisioned.DeepCopy()
	out.Used = in.Used.DeepCopy()
	out.Free = in.Free.DeepCopy()
	out.Total = in.Total.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogicalVolumeCapacity.
func (in *LogicalVolumeCapacity) DeepCopy() *LogicalVolumeCapacity {
	if in == nil {
		return nil
	}
	out := new(LogicalVolumeCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogicalVolumeMetrics) DeepCopyInto(out *LogicalVolumeMetrics) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	in.Capacity.DeepCopyInto(&out.Capacity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogicalVolumeMetrics.
func (in *LogicalVolumeMetrics) DeepCopy() *LogicalVolumeMetrics {
	if in == nil {
		return nil
	}
	out := new(LogicalVolumeMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogicalVolumeMetrics) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogicalVolumeMetricsList) DeepCopyInto(out *LogicalVolumeMetricsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogicalVolumeMetrics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogicalVolumeMetricsList.
func (in *LogicalVolumeMetricsList) DeepCopy() *LogicalVolumeMetricsList {
	if in == nil {
		return nil
	}
	out := new(LogicalVolumeMetricsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogicalVolumeMetricsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDeviceCapacity) DeepCopyInto(out *StorageDeviceCapacity) {
	*out = *in
	out.Total = in.Total.DeepCopy()
	out.Used = in.Used.DeepCopy()
	out.Free = in.Free.DeepCopy()
	out.Provisioned = in.Provisioned.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDeviceCapacity.
func (in *StorageDeviceCapacity) DeepCopy() *StorageDeviceCapacity {
	if in == nil {
		return nil
	}
	out := new(StorageDeviceCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDeviceMetrics) DeepCopyInto(out *StorageDeviceMetrics) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	in.Capacity.DeepCopyInto(&out.Capacity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDeviceMetrics.
func (in *StorageDeviceMetrics) DeepCopy() *StorageDeviceMetrics {
	if in == nil {
		return nil
	}
	out := new(StorageDeviceMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageDeviceMetrics) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageDeviceMetricsList) DeepCopyInto(out *StorageDeviceMetricsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageDeviceMetrics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageDeviceMetricsList.
func (in *StorageDeviceMetricsList) DeepCopy() *StorageDeviceMetricsList {
	if in == nil {
		return nil
	}
	out := new(StorageDeviceMetricsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageDeviceMetricsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolCapacity) DeepCopyInto(out *StoragePoolCapacity) {
	*out = *in
	out.Total = in.Total.DeepCopy()
	out.Used = in.Used.DeepCopy()
	out.Free = in.Free.DeepCopy()
	out.Provisioned = in.Provisioned.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolCapacity.
func (in *StoragePoolCapacity) DeepCopy() *StoragePoolCapacity {
	if in == nil {
		return nil
	}
	out := new(StoragePoolCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolMetrics) DeepCopyInto(out *StoragePoolMetrics) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	in.Capacity.DeepCopyInto(&out.Capacity)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolMetrics.
func (in *StoragePoolMetrics) DeepCopy() *StoragePoolMetrics {
	if in == nil {
		return nil
	}
	out := new(StoragePoolMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePoolMetrics) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoragePoolMetricsList) DeepCopyInto(out *StoragePoolMetricsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StoragePoolMetrics, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoragePoolMetricsList.
func (in *StoragePoolMetricsList) DeepCopy() *StoragePoolMetricsList {
	if in == nil {
		return nil
	}
	out := new(StoragePoolMetricsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StoragePoolMetricsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
