apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: spdkcsi-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: simplyblock-csi-sc
