---
apiVersion: v1
kind: Pod
metadata:
  name: persist-write
  labels:
    app: persist-write
spec:
  restartPolicy: Never
  containers:
  - name: fio
    image: dockerpinata/fio:2.1
    imagePullPolicy: IfNotPresent
    command: ["fio"]
    args:
    - --name=write
    - --rw=write
    - --bs=128k
    - --numjobs=1
    - --size=1g
    - --filename=/data/fio.dat
    - --ioengine=libaio
    - --iodepth=32
    - --direct=1
    - --verify=md5
    - --verify_fatal=1
    - --end_fsync=1
    volumeMounts:
    - mountPath: /data
      name: vol
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: persist-pvc
