---
apiVersion: v1
kind: Pod
metadata:
  name: persist-verify
  labels:
    app: persist-verify
spec:
  restartPolicy: Never
  containers:
  - name: fio
    image: dockerpinata/fio:2.1
    imagePullPolicy: IfNotPresent
    command: ["fio"]
    args:
    - --name=verify
    - --rw=read
    - --bs=16k
    - --numjobs=1
    - --size=1g
    - --filename=/data/fio.dat
    - --ioengine=libaio
    - --iodepth=1
    - --direct=1
    - --verify=md5
    - --verify_only
    - --verify_fatal=1
    - --verify_dump=1
    volumeMounts:
    - mountPath: /data
      name: vol
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: persist-pvc
