---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.simplyblock.io
  resources:
  - devices
  - lvols
  - pools
  - snapshotreplications
  - storagebackups
  - storageclusters
  - storagenodes
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.simplyblock.io
  resources:
  - devices/finalizers
  - lvols/finalizers
  - pools/finalizers
  - snapshotreplications/finalizers
  - storagebackups/finalizers
  - storageclusters/finalizers
  - storagenodes/finalizers
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - storage.simplyblock.io
  resources:
  - devices/status
  - lvols/status
  - pools/status
  - snapshotreplications/status
  - storagebackups/status
  - storageclusters/status
  - storagenodes/status
  - tasks/status
  verbs:
  - get
  - patch
  - update
