---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - simplyblock.simplyblock.io
  resources:
  - simplyblockdevices
  - simplyblockpools
  - simplyblockstorageclusters
  - simplyblockstoragenodes
  - simplyblocktasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - simplyblock.simplyblock.io
  resources:
  - simplyblockdevices/finalizers
  - simplyblockpools/finalizers
  - simplyblockstorageclusters/finalizers
  - simplyblockstoragenodes/finalizers
  - simplyblocktasks/finalizers
  verbs:
  - update
- apiGroups:
  - simplyblock.simplyblock.io
  resources:
  - simplyblockdevices/status
  - simplyblockpools/status
  - simplyblockstorageclusters/status
  - simplyblockstoragenodes/status
  - simplyblocktasks/status
  verbs:
  - get
  - patch
  - update
