---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.simplyblock.io
  resources:
  - devices
  - lvols
  - pools
  - storageclusters
  - storagenodes
  - tasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.simplyblock.io
  resources:
  - devices/finalizers
  - lvols/finalizers
  - pools/finalizers
  - storageclusters/finalizers
  - storagenodes/finalizers
  - tasks/finalizers
  verbs:
  - update
- apiGroups:
  - storage.simplyblock.io
  resources:
  - devices/status
  - lvols/status
  - pools/status
  - storageclusters/status
  - storagenodes/status
  - tasks/status
  verbs:
  - get
  - patch
  - update
