# This rule is not used by the project simplyblock-manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only permissions on the project simplyblock-manager API group.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simplyblock-manager
    app.kubernetes.io/managed-by: kustomize
  name: simplyblockrestore-viewer-role
rules:
- apiGroups:
  - simplyblock.simplyblock.io
  resources:
  - simplyblockrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - simplyblock.simplyblock.io
  resources:
  - simplyblockrestores/status
  verbs:
  - get
