// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: export.proto

// Package atlas.nfsexport.v1 carries pNFS export assembly to the host that
// serves it.
//
// Unlike atlas.storage.v1, which is read-only by construction, everything here
// mutates the node: it makes filesystems, mounts them, and publishes them. That
// is why it is a separate service rather than more methods on the storage one --
// a credential can be granted the reading and not the writing.
//
// The operator is the only caller. No consuming pod runs on the host that serves
// an export, so kubelet never issues a stage for it and something else has to
// ask; this is that something.

package nfsexportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExportSpec is one export: which device, where it goes, and who may mount it.
// It mirrors export.Spec field for field.
type ExportSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_uuid identifies the backing namespace: for a simplyblock volume the
	// namespace UUID is the logical volume's own id. It is the identifier rather
	// than a device path because a path is assigned in attach order and differs
	// across hosts, while this is a property of the namespace.
	//
	// It is the UUID rather than the NGUID because the UUID is what the control
	// plane knows when it provisions; the NGUID is assigned by the target and
	// read back from the device.
	VolumeUuid string `protobuf:"bytes,1,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	// path is the mount point and the exported directory.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// fsid is what the export is published under. Holding it stable across hosts
	// is what lets a re-materialized export reproduce the file handles clients
	// already hold.
	Fsid string `protobuf:"bytes,3,opt,name=fsid,proto3" json:"fsid,omitempty"`
	// clients is the set allowed to mount, as exports(5) spells it. An empty set
	// is refused rather than widened to everyone.
	Clients []string `protobuf:"bytes,4,rep,name=clients,proto3" json:"clients,omitempty"`
	// cluster_id and pool_id identify the volume to the control plane, which is
	// what the host needs to ask where the namespace is served from and to be
	// allowed to connect to it. They do not find the device -- volume_uuid does
	// that -- and a host that does not attach its own namespaces ignores them.
	ClusterId string `protobuf:"bytes,5,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	PoolId    string `protobuf:"bytes,6,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// encrypted tells the assembler to open the backing namespace before
	// inspecting or formatting its filesystem.
	Encrypted bool `protobuf:"varint,7,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	// host_nqn is the NVMe host identity to attach the namespace as, when the
	// caller decides it: a pNFS metadata server pod is one host across
	// restarts, which its own kernel cannot know. Empty lets the host derive
	// its own.
	HostNqn string `protobuf:"bytes,8,opt,name=host_nqn,json=hostNqn,proto3" json:"host_nqn,omitempty"`
	// connection is where the namespace is served from, resolved by the caller
	// for a host that cannot reach the control plane itself. Absent leaves
	// resolving it to the host. It carries DHCHAP secrets, so it is sent only
	// from the metadata server pod to its own guest, never by the operator.
	Connection    *Connection `protobuf:"bytes,9,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSpec) Reset() {
	*x = ExportSpec{}
	mi := &file_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSpec) ProtoMessage() {}

func (x *ExportSpec) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSpec.ProtoReflect.Descriptor instead.
func (*ExportSpec) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportSpec) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *ExportSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExportSpec) GetFsid() string {
	if x != nil {
		return x.Fsid
	}
	return ""
}

func (x *ExportSpec) GetClients() []string {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ExportSpec) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ExportSpec) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *ExportSpec) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

func (x *ExportSpec) GetHostNqn() string {
	if x != nil {
		return x.HostNqn
	}
	return ""
}

func (x *ExportSpec) GetConnection() *Connection {
	if x != nil {
		return x.Connection
	}
	return nil
}

// Connection mirrors lvol.Connection: the subsystem and the paths to it, in the
// control plane's priority order.
type Connection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nqn           string                 `protobuf:"bytes,1,opt,name=nqn,proto3" json:"nqn,omitempty"`
	Nsid          uint32                 `protobuf:"varint,2,opt,name=nsid,proto3" json:"nsid,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Endpoints     []*Endpoint            `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connection) Reset() {
	*x = Connection{}
	mi := &file_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connection) ProtoMessage() {}

func (x *Connection) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connection.ProtoReflect.Descriptor instead.
func (*Connection) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{1}
}

func (x *Connection) GetNqn() string {
	if x != nil {
		return x.Nqn
	}
	return ""
}

func (x *Connection) GetNsid() uint32 {
	if x != nil {
		return x.Nsid
	}
	return 0
}

func (x *Connection) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Connection) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// Endpoint mirrors lvol.Endpoint, one path to the subsystem. The two timeouts
// are optional because zero ("fail at once") and unset ("the connector's
// default") behave differently.
type Endpoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Transport         string                 `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port              int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	NrIoQueues        int32                  `protobuf:"varint,4,opt,name=nr_io_queues,json=nrIoQueues,proto3" json:"nr_io_queues,omitempty"`
	ReconnectDelaySec int32                  `protobuf:"varint,5,opt,name=reconnect_delay_sec,json=reconnectDelaySec,proto3" json:"reconnect_delay_sec,omitempty"`
	KeepAliveTmoSec   int32                  `protobuf:"varint,6,opt,name=keep_alive_tmo_sec,json=keepAliveTmoSec,proto3" json:"keep_alive_tmo_sec,omitempty"`
	CtrlLossTmoSec    *int32                 `protobuf:"varint,7,opt,name=ctrl_loss_tmo_sec,json=ctrlLossTmoSec,proto3,oneof" json:"ctrl_loss_tmo_sec,omitempty"`
	FastIoFailTmoSec  *int32                 `protobuf:"varint,8,opt,name=fast_io_fail_tmo_sec,json=fastIoFailTmoSec,proto3,oneof" json:"fast_io_fail_tmo_sec,omitempty"`
	HostIface         string                 `protobuf:"bytes,9,opt,name=host_iface,json=hostIface,proto3" json:"host_iface,omitempty"`
	Tls               bool                   `protobuf:"varint,10,opt,name=tls,proto3" json:"tls,omitempty"`
	DhchapSecret      string                 `protobuf:"bytes,11,opt,name=dhchap_secret,json=dhchapSecret,proto3" json:"dhchap_secret,omitempty"`
	DhchapCtrlSecret  string                 `protobuf:"bytes,12,opt,name=dhchap_ctrl_secret,json=dhchapCtrlSecret,proto3" json:"dhchap_ctrl_secret,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{2}
}

func (x *Endpoint) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *Endpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Endpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Endpoint) GetNrIoQueues() int32 {
	if x != nil {
		return x.NrIoQueues
	}
	return 0
}

func (x *Endpoint) GetReconnectDelaySec() int32 {
	if x != nil {
		return x.ReconnectDelaySec
	}
	return 0
}

func (x *Endpoint) GetKeepAliveTmoSec() int32 {
	if x != nil {
		return x.KeepAliveTmoSec
	}
	return 0
}

func (x *Endpoint) GetCtrlLossTmoSec() int32 {
	if x != nil && x.CtrlLossTmoSec != nil {
		return *x.CtrlLossTmoSec
	}
	return 0
}

func (x *Endpoint) GetFastIoFailTmoSec() int32 {
	if x != nil && x.FastIoFailTmoSec != nil {
		return *x.FastIoFailTmoSec
	}
	return 0
}

func (x *Endpoint) GetHostIface() string {
	if x != nil {
		return x.HostIface
	}
	return ""
}

func (x *Endpoint) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *Endpoint) GetDhchapSecret() string {
	if x != nil {
		return x.DhchapSecret
	}
	return ""
}

func (x *Endpoint) GetDhchapCtrlSecret() string {
	if x != nil {
		return x.DhchapCtrlSecret
	}
	return ""
}

type CreateExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ExportSpec            `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExportRequest) Reset() {
	*x = CreateExportRequest{}
	mi := &file_export_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExportRequest) ProtoMessage() {}

func (x *CreateExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExportRequest.ProtoReflect.Descriptor instead.
func (*CreateExportRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{3}
}

func (x *CreateExportRequest) GetSpec() *ExportSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExportResponse) Reset() {
	*x = CreateExportResponse{}
	mi := &file_export_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExportResponse) ProtoMessage() {}

func (x *CreateExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExportResponse.ProtoReflect.Descriptor instead.
func (*CreateExportResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{4}
}

type DeleteExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ExportSpec            `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExportRequest) Reset() {
	*x = DeleteExportRequest{}
	mi := &file_export_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExportRequest) ProtoMessage() {}

func (x *DeleteExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExportRequest.ProtoReflect.Descriptor instead.
func (*DeleteExportRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteExportRequest) GetSpec() *ExportSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeleteExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExportResponse) Reset() {
	*x = DeleteExportResponse{}
	mi := &file_export_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExportResponse) ProtoMessage() {}

func (x *DeleteExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExportResponse.ProtoReflect.Descriptor instead.
func (*DeleteExportResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{6}
}

type CheckExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ExportSpec            `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExportRequest) Reset() {
	*x = CheckExportRequest{}
	mi := &file_export_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExportRequest) ProtoMessage() {}

func (x *CheckExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExportRequest.ProtoReflect.Descriptor instead.
func (*CheckExportRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{7}
}

func (x *CheckExportRequest) GetSpec() *ExportSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CheckExportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy is false whenever the node found a reason the export is not
	// actually being served. reason says which.
	Healthy       bool   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExportResponse) Reset() {
	*x = CheckExportResponse{}
	mi := &file_export_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExportResponse) ProtoMessage() {}

func (x *CheckExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExportResponse.ProtoReflect.Descriptor instead.
func (*CheckExportResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{8}
}

func (x *CheckExportResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *CheckExportResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type FileExtentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The export's path, as in ExportSpec.path.
	ExportPath string `protobuf:"bytes,1,opt,name=export_path,json=exportPath,proto3" json:"export_path,omitempty"`
	// A file directly inside the export, by name.
	File          string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Offset        uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileExtentsRequest) Reset() {
	*x = FileExtentsRequest{}
	mi := &file_export_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileExtentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileExtentsRequest) ProtoMessage() {}

func (x *FileExtentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileExtentsRequest.ProtoReflect.Descriptor instead.
func (*FileExtentsRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{9}
}

func (x *FileExtentsRequest) GetExportPath() string {
	if x != nil {
		return x.ExportPath
	}
	return ""
}

func (x *FileExtentsRequest) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *FileExtentsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileExtentsRequest) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type FileExtentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The file's size as the server knows it.
	Size          uint64         `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Pieces        []*ExtentPiece `protobuf:"bytes,2,rep,name=pieces,proto3" json:"pieces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileExtentsResponse) Reset() {
	*x = FileExtentsResponse{}
	mi := &file_export_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileExtentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileExtentsResponse) ProtoMessage() {}

func (x *FileExtentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileExtentsResponse.ProtoReflect.Descriptor instead.
func (*FileExtentsResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{10}
}

func (x *FileExtentsResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileExtentsResponse) GetPieces() []*ExtentPiece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

type ExtentPiece struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Offset uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Length uint64                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	// written, unwritten, delalloc, or hole.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Device offset of the first byte of the piece. Zero for a hole or delalloc.
	Physical      uint64 `protobuf:"varint,4,opt,name=physical,proto3" json:"physical,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtentPiece) Reset() {
	*x = ExtentPiece{}
	mi := &file_export_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtentPiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtentPiece) ProtoMessage() {}

func (x *ExtentPiece) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtentPiece.ProtoReflect.Descriptor instead.
func (*ExtentPiece) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{11}
}

func (x *ExtentPiece) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ExtentPiece) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ExtentPiece) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExtentPiece) GetPhysical() uint64 {
	if x != nil {
		return x.Physical
	}
	return 0
}

var File_export_proto protoreflect.FileDescriptor

const file_export_proto_rawDesc = "" +
	"\n" +
	"\fexport.proto\x12\x12atlas.nfsexport.v1\"\xa0\x02\n" +
	"\n" +
	"ExportSpec\x12\x1f\n" +
	"\vvolume_uuid\x18\x01 \x01(\tR\n" +
	"volumeUuid\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04fsid\x18\x03 \x01(\tR\x04fsid\x12\x18\n" +
	"\aclients\x18\x04 \x03(\tR\aclients\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x05 \x01(\tR\tclusterId\x12\x17\n" +
	"\apool_id\x18\x06 \x01(\tR\x06poolId\x12\x1c\n" +
	"\tencrypted\x18\a \x01(\bR\tencrypted\x12\x19\n" +
	"\bhost_nqn\x18\b \x01(\tR\ahostNqn\x12>\n" +
	"\n" +
	"connection\x18\t \x01(\v2\x1e.atlas.nfsexport.v1.ConnectionR\n" +
	"connection\"\x82\x01\n" +
	"\n" +
	"Connection\x12\x10\n" +
	"\x03nqn\x18\x01 \x01(\tR\x03nqn\x12\x12\n" +
	"\x04nsid\x18\x02 \x01(\rR\x04nsid\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12:\n" +
	"\tendpoints\x18\x04 \x03(\v2\x1c.atlas.nfsexport.v1.EndpointR\tendpoints\"\xed\x03\n" +
	"\bEndpoint\x12\x1c\n" +
	"\ttransport\x18\x01 \x01(\tR\ttransport\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12 \n" +
	"\fnr_io_queues\x18\x04 \x01(\x05R\n" +
	"nrIoQueues\x12.\n" +
	"\x13reconnect_delay_sec\x18\x05 \x01(\x05R\x11reconnectDelaySec\x12+\n" +
	"\x12keep_alive_tmo_sec\x18\x06 \x01(\x05R\x0fkeepAliveTmoSec\x12.\n" +
	"\x11ctrl_loss_tmo_sec\x18\a \x01(\x05H\x00R\x0ectrlLossTmoSec\x88\x01\x01\x123\n" +
	"\x14fast_io_fail_tmo_sec\x18\b \x01(\x05H\x01R\x10fastIoFailTmoSec\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"host_iface\x18\t \x01(\tR\thostIface\x12\x10\n" +
	"\x03tls\x18\n" +
	" \x01(\bR\x03tls\x12#\n" +
	"\rdhchap_secret\x18\v \x01(\tR\fdhchapSecret\x12,\n" +
	"\x12dhchap_ctrl_secret\x18\f \x01(\tR\x10dhchapCtrlSecretB\x14\n" +
	"\x12_ctrl_loss_tmo_secB\x17\n" +
	"\x15_fast_io_fail_tmo_sec\"I\n" +
	"\x13CreateExportRequest\x122\n" +
	"\x04spec\x18\x01 \x01(\v2\x1e.atlas.nfsexport.v1.ExportSpecR\x04spec\"\x16\n" +
	"\x14CreateExportResponse\"I\n" +
	"\x13DeleteExportRequest\x122\n" +
	"\x04spec\x18\x01 \x01(\v2\x1e.atlas.nfsexport.v1.ExportSpecR\x04spec\"\x16\n" +
	"\x14DeleteExportResponse\"H\n" +
	"\x12CheckExportRequest\x122\n" +
	"\x04spec\x18\x01 \x01(\v2\x1e.atlas.nfsexport.v1.ExportSpecR\x04spec\"G\n" +
	"\x13CheckExportResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"y\n" +
	"\x12FileExtentsRequest\x12\x1f\n" +
	"\vexport_path\x18\x01 \x01(\tR\n" +
	"exportPath\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\"b\n" +
	"\x13FileExtentsResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x127\n" +
	"\x06pieces\x18\x02 \x03(\v2\x1f.atlas.nfsexport.v1.ExtentPieceR\x06pieces\"m\n" +
	"\vExtentPiece\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x04R\x06length\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1a\n" +
	"\bphysical\x18\x04 \x01(\x04R\bphysical2\x95\x03\n" +
	"\rExportService\x12a\n" +
	"\fCreateExport\x12'.atlas.nfsexport.v1.CreateExportRequest\x1a(.atlas.nfsexport.v1.CreateExportResponse\x12a\n" +
	"\fDeleteExport\x12'.atlas.nfsexport.v1.DeleteExportRequest\x1a(.atlas.nfsexport.v1.DeleteExportResponse\x12^\n" +
	"\vCheckExport\x12&.atlas.nfsexport.v1.CheckExportRequest\x1a'.atlas.nfsexport.v1.CheckExportResponse\x12^\n" +
	"\vFileExtents\x12&.atlas.nfsexport.v1.FileExtentsRequest\x1a'.atlas.nfsexport.v1.FileExtentsResponseBMZKgithub.com/simplyblock/atlas/nfsexport/nfsexportrpc/nfsexportv1;nfsexportv1b\x06proto3"

var (
	file_export_proto_rawDescOnce sync.Once
	file_export_proto_rawDescData []byte
)

func file_export_proto_rawDescGZIP() []byte {
	file_export_proto_rawDescOnce.Do(func() {
		file_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)))
	})
	return file_export_proto_rawDescData
}

var file_export_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_export_proto_goTypes = []any{
	(*ExportSpec)(nil),           // 0: atlas.nfsexport.v1.ExportSpec
	(*Connection)(nil),           // 1: atlas.nfsexport.v1.Connection
	(*Endpoint)(nil),             // 2: atlas.nfsexport.v1.Endpoint
	(*CreateExportRequest)(nil),  // 3: atlas.nfsexport.v1.CreateExportRequest
	(*CreateExportResponse)(nil), // 4: atlas.nfsexport.v1.CreateExportResponse
	(*DeleteExportRequest)(nil),  // 5: atlas.nfsexport.v1.DeleteExportRequest
	(*DeleteExportResponse)(nil), // 6: atlas.nfsexport.v1.DeleteExportResponse
	(*CheckExportRequest)(nil),   // 7: atlas.nfsexport.v1.CheckExportRequest
	(*CheckExportResponse)(nil),  // 8: atlas.nfsexport.v1.CheckExportResponse
	(*FileExtentsRequest)(nil),   // 9: atlas.nfsexport.v1.FileExtentsRequest
	(*FileExtentsResponse)(nil),  // 10: atlas.nfsexport.v1.FileExtentsResponse
	(*ExtentPiece)(nil),          // 11: atlas.nfsexport.v1.ExtentPiece
}
var file_export_proto_depIdxs = []int32{
	1,  // 0: atlas.nfsexport.v1.ExportSpec.connection:type_name -> atlas.nfsexport.v1.Connection
	2,  // 1: atlas.nfsexport.v1.Connection.endpoints:type_name -> atlas.nfsexport.v1.Endpoint
	0,  // 2: atlas.nfsexport.v1.CreateExportRequest.spec:type_name -> atlas.nfsexport.v1.ExportSpec
	0,  // 3: atlas.nfsexport.v1.DeleteExportRequest.spec:type_name -> atlas.nfsexport.v1.ExportSpec
	0,  // 4: atlas.nfsexport.v1.CheckExportRequest.spec:type_name -> atlas.nfsexport.v1.ExportSpec
	11, // 5: atlas.nfsexport.v1.FileExtentsResponse.pieces:type_name -> atlas.nfsexport.v1.ExtentPiece
	3,  // 6: atlas.nfsexport.v1.ExportService.CreateExport:input_type -> atlas.nfsexport.v1.CreateExportRequest
	5,  // 7: atlas.nfsexport.v1.ExportService.DeleteExport:input_type -> atlas.nfsexport.v1.DeleteExportRequest
	7,  // 8: atlas.nfsexport.v1.ExportService.CheckExport:input_type -> atlas.nfsexport.v1.CheckExportRequest
	9,  // 9: atlas.nfsexport.v1.ExportService.FileExtents:input_type -> atlas.nfsexport.v1.FileExtentsRequest
	4,  // 10: atlas.nfsexport.v1.ExportService.CreateExport:output_type -> atlas.nfsexport.v1.CreateExportResponse
	6,  // 11: atlas.nfsexport.v1.ExportService.DeleteExport:output_type -> atlas.nfsexport.v1.DeleteExportResponse
	8,  // 12: atlas.nfsexport.v1.ExportService.CheckExport:output_type -> atlas.nfsexport.v1.CheckExportResponse
	10, // 13: atlas.nfsexport.v1.ExportService.FileExtents:output_type -> atlas.nfsexport.v1.FileExtentsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_export_proto_init() }
func file_export_proto_init() {
	if File_export_proto != nil {
		return
	}
	file_export_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_export_proto_goTypes,
		DependencyIndexes: file_export_proto_depIdxs,
		MessageInfos:      file_export_proto_msgTypes,
	}.Build()
	File_export_proto = out.File
	file_export_proto_goTypes = nil
	file_export_proto_depIdxs = nil
}
