apiVersion: storage.simplyblock.io/v1alpha1
kind: StorageCluster
metadata:
  name: simplyblock-cluster
  namespace: simplyblock
spec:
  clusterName: simplyblock-cluster
  mgmtIfname: br-ex
  fabricType: tcp
  isSingleNode: false
  enableNodeAffinity: false
  strictNodeAntiAffinity: false
  stripe:
    dataChunks: 1
    parityChunks: 1
  warningThreshold:
    capacity: 80
    provisionedCapacity: 80
  criticalThreshold:
    capacity: 90
    provisionedCapacity: 90

---
apiVersion: storage.simplyblock.io/v1alpha1
kind: Pool
metadata:
  name: simplyblock-pool
  namespace: simplyblock
spec:
  name: simplyblock-pool
  clusterName: simplyblock-cluster

---
apiVersion: storage.simplyblock.io/v1alpha1
kind: StorageNode
metadata:
  name: simplyblock-node
  namespace: simplyblock
spec:
  clusterName: simplyblock-cluster
  clusterImage: "quay.io/simplyblock-io/simplyblock:26.2.2-PRE"
  mgmtIfname: br-ex
  maxLogicalVolumeCount: 100
  partitions: 1
  corePercentage: 25
  coreIsolation: false
  socketsToUse:
    - "0"
  dataIfname:
    - br-ex
  journalManager:
    count: 3
    percentPerDevice: 3
  skipKubeletConfiguration: false
  enableCpuTopology: true
  openShiftCluster: true
  ubuntuHost: false
  forceFormat4K: true
  workerNodes: []
