{{- if and .Values.operator.enabled .Values.controlplane.observability.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simplyblock-fluent-bit-sa
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simplyblock-fluent-bit-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: simplyblock-fluent-bit-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simplyblock-fluent-bit-role
subjects:
  - kind: ServiceAccount
    name: simplyblock-fluent-bit-sa
    namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simplyblock-fluent-bit
  namespace: {{ .Release.Namespace }}
  labels:
    app: simplyblock-fluent-bit
spec:
  selector:
    matchLabels:
      app: simplyblock-fluent-bit
  template:
    metadata:
      labels:
        app: simplyblock-fluent-bit
    spec:
      serviceAccountName: simplyblock-fluent-bit-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: io.simplyblock.node-type
                operator: Exists
            {{- if .Values.controlplane.nodeSelector.create }}
            - matchExpressions:
              - key: {{ .Values.controlplane.nodeSelector.key }}
                operator: In
                values:
                - {{ .Values.controlplane.nodeSelector.value }}
            {{- end }}
      {{- if .Values.controlplane.tolerations.create }}
      tolerations:
      {{- range .Values.controlplane.tolerations.list }}
      - operator: {{ .operator | quote }}
        {{- if .effect }}
        effect: {{ .effect | quote }}
        {{- end }}
        {{- if .key }}
        key: {{ .key | quote }}
        {{- end }}
        {{- if .value }}
        value: {{ .value | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      containers:
        - name: fluent-bit
          image: {{ .Values.controlplane.observability.fluentbit.repository }}:{{ .Values.controlplane.observability.fluentbit.tag }}
          imagePullPolicy: {{ .Values.controlplane.observability.fluentbit.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: config
              mountPath: /fluent-bit/etc/
            - name: flb-db
              mountPath: /var/flb-db
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config
          configMap:
            name: simplyblock-fluent-bit-config
        - name: flb-db
          hostPath:
            path: /var/simplyblock/flb-db
            type: DirectoryOrCreate
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

{{- end -}}
