// Code generated by ./gen; DO NOT EDIT.
//
// A 501 stub for each of cpsim.gen.go's 98 endpoints that handlers.go does not implement.
// 9 are implemented; the rest answer "not implemented," which is a truthful
// answer and a distinguishable one — a 404 from here would look like a missing
// volume rather than a missing simulator.
//
// A new stub in this file means the control-plane spec grew an endpoint.

package cpsim

import (
	"net/http"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// The simulator satisfies the whole generated interface.
var _ ServerInterface = (*Server)(nil)

// Implemented in handlers.go:
//   ClustersStorageNodesDetailApiV2ClustersClusterIdStorageNodesStorageNodeIdGet
//   ClustersStorageNodesListApiV2ClustersClusterIdStorageNodesGet
//   ClustersStoragePoolsDetailApiV2ClustersClusterIdStoragePoolsPoolIdGet
//   ClustersStoragePoolsListApiV2ClustersClusterIdStoragePoolsGet
//   ClustersStoragePoolsVolumesConnectApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdConnectGet
//   ClustersStoragePoolsVolumesDetailApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdGet
//   ClustersStoragePoolsVolumesListApiV2ClustersClusterIdStoragePoolsPoolIdVolumesGet
//   HealthApiV2MetaHealthGet
//   ReadyApiV2MetaReadyGet

func (s *Server) ClustersListApiV2ClustersGet(w http.ResponseWriter, r *http.Request, _ ClustersListApiV2ClustersGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersCreateApiV2ClustersPost(w http.ResponseWriter, r *http.Request, _ ClustersCreateApiV2ClustersPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersDeleteApiV2ClustersClusterIdDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersDetailApiV2ClustersClusterIdGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersUpdateApiV2ClustersClusterIdPut(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersActivateApiV2ClustersClusterIdActivatePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersAddreplicationApiV2ClustersClusterIdAddreplicationPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsListApiV2ClustersClusterIdBackupsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsCreateApiV2ClustersClusterIdBackupsPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ ClustersBackupsCreateApiV2ClustersClusterIdBackupsPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupPoliciesListApiV2ClustersClusterIdBackupsBackupPoliciesGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupPoliciesCreateApiV2ClustersClusterIdBackupsBackupPoliciesPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupPoliciesDeleteApiV2ClustersClusterIdBackupsBackupPoliciesPolicyIdDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupPoliciesAttachApiV2ClustersClusterIdBackupsBackupPoliciesPolicyIdAttachPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupPoliciesDetachApiV2ClustersClusterIdBackupsBackupPoliciesPolicyIdDetachPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsExportApiV2ClustersClusterIdBackupsExportGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ ClustersBackupsExportApiV2ClustersClusterIdBackupsExportGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsImportApiV2ClustersClusterIdBackupsImportPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsRestoreApiV2ClustersClusterIdBackupsRestorePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsSourceSwitchApiV2ClustersClusterIdBackupsSourceSwitchPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsSourcesApiV2ClustersClusterIdBackupsSourcesGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsDetailApiV2ClustersClusterIdBackupsBackupIdGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersBackupsDeleteApiV2ClustersClusterIdBackupsVolumeIdDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersCapacityApiV2ClustersClusterIdCapacityGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ ClustersCapacityApiV2ClustersClusterIdCapacityGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersExpandApiV2ClustersClusterIdExpandPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersIostatsApiV2ClustersClusterIdIostatsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ ClustersIostatsApiV2ClustersClusterIdIostatsGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersLogsApiV2ClustersClusterIdLogsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ ClustersLogsApiV2ClustersClusterIdLogsGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersRebalanceApiV2ClustersClusterIdRebalancePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersShutdownApiV2ClustersClusterIdShutdownPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStartApiV2ClustersClusterIdStartPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesCreateApiV2ClustersClusterIdStorageNodesPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ ClustersStorageNodesCreateApiV2ClustersClusterIdStorageNodesPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDeleteApiV2ClustersClusterIdStorageNodesStorageNodeIdDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesDeleteApiV2ClustersClusterIdStorageNodesStorageNodeIdDeleteParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesCapacityApiV2ClustersClusterIdStorageNodesStorageNodeIdCapacityGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesCapacityApiV2ClustersClusterIdStorageNodesStorageNodeIdCapacityGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDevicesListApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDevicesDetailApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDevicesCapacityApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdCapacityGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesDevicesCapacityApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdCapacityGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDevicesGetDeviceHealthInfoApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdHealthInfoGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDevicesIostatsApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdIostatsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesDevicesIostatsApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdIostatsGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDevicesRemoveApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdRemovePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesDevicesRemoveApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdRemovePostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDevicesResetApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdResetPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesDevicesRestartApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdRestartPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesDevicesRestartApiV2ClustersClusterIdStorageNodesStorageNodeIdDevicesDeviceIdRestartPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesIostatsApiV2ClustersClusterIdStorageNodesStorageNodeIdIostatsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesIostatsApiV2ClustersClusterIdStorageNodesStorageNodeIdIostatsGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesNicsListApiV2ClustersClusterIdStorageNodesStorageNodeIdNicsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesNicsIostatsApiV2ClustersClusterIdStorageNodesStorageNodeIdNicsNicIdIostatsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ string) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesStartApiV2ClustersClusterIdStorageNodesStorageNodeIdPromotePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesRestartApiV2ClustersClusterIdStorageNodesStorageNodeIdRestartPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesResumeApiV2ClustersClusterIdStorageNodesStorageNodeIdResumePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesShutdownApiV2ClustersClusterIdStorageNodesStorageNodeIdShutdownPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesShutdownApiV2ClustersClusterIdStorageNodesStorageNodeIdShutdownPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesStartApiV2ClustersClusterIdStorageNodesStorageNodeIdStartPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStorageNodesSuspendApiV2ClustersClusterIdStorageNodesStorageNodeIdSuspendPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStorageNodesSuspendApiV2ClustersClusterIdStorageNodesStorageNodeIdSuspendPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsCreateApiV2ClustersClusterIdStoragePoolsPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ ClustersStoragePoolsCreateApiV2ClustersClusterIdStoragePoolsPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsDeleteApiV2ClustersClusterIdStoragePoolsPoolIdDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsUpdateApiV2ClustersClusterIdStoragePoolsPoolIdPut(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsRemoveHostApiV2ClustersClusterIdStoragePoolsPoolIdHostDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsAddHostApiV2ClustersClusterIdStoragePoolsPoolIdHostPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsIostatsApiV2ClustersClusterIdStoragePoolsPoolIdIostatsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStoragePoolsIostatsApiV2ClustersClusterIdStoragePoolsPoolIdIostatsGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsSnapshotsListApiV2ClustersClusterIdStoragePoolsPoolIdSnapshotsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsSnapshotsDeleteApiV2ClustersClusterIdStoragePoolsPoolIdSnapshotsSnapshotIdDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsSnapshotsDetailApiV2ClustersClusterIdStoragePoolsPoolIdSnapshotsSnapshotIdGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesCreateApiV2ClustersClusterIdStoragePoolsPoolIdVolumesPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStoragePoolsVolumesCreateApiV2ClustersClusterIdStoragePoolsPoolIdVolumesPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsReplicateLvolOnSourceClusterApiV2ClustersClusterIdStoragePoolsPoolIdVolumesReplicateLvolOnSourceClusterPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesDeleteApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesUpdateApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdPut(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesBackupsDeleteApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdBackupsDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesBackupsListApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdBackupsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesCapacityApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdCapacityGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStoragePoolsVolumesCapacityApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdCapacityGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesCloneApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdClonePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStoragePoolsVolumesCloneApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdClonePostParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesAddHostApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdHostsPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesRemoveHostApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdHostsHostNqnDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ string) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesGetHostSecretApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdHostsHostNqnSecretGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ string) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesInflateApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdInflatePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesIostatsApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdIostatsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ ClustersStoragePoolsVolumesIostatsApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdIostatsGetParams) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesListReplicationTasksApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdListReplicationTasksGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesMigrationsListApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdMigrationsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClusterStoragePoolsVolumesMigrationsCreateApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdMigrationsPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ ClusterStoragePoolsVolumesMigrationsCreateApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdMigrationsPostParams) {
	notImplemented(w, r)
}

func (s *Server) ClusterStoragePoolsVolumesMigrationsCancelApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdMigrationsMigrationIdDelete(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClusterStoragePoolsVolumesMigrationsDetailApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdMigrationsMigrationIdGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClusterStoragePoolsVolumesMigrationsContinueApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdMigrationsMigrationIdContinuePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesReplicateLvolApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdReplicateLvolPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesReplicationCommitApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdReplicationCommitPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesReplicationFailbackApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdReplicationFailbackPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesReplicationStartApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdReplicationStartPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesReplicationStopApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdReplicationStopPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesReplicationStartApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdReplicationTriggerPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesSnapshotsListApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdSnapshotsGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersStoragePoolsVolumesSnapshotsCreateApiV2ClustersClusterIdStoragePoolsPoolIdVolumesVolumeIdSnapshotsPost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersTasksListApiV2ClustersClusterIdTasksGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersTasksDetailApiV2ClustersClusterIdTasksTaskIdGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ClustersUpgradeApiV2ClustersClusterIdUpdatePost(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID) {
	notImplemented(w, r)
}

func (s *Server) ManagementNodesListApiV2ManagementNodesGet(w http.ResponseWriter, r *http.Request, _ ManagementNodesListApiV2ManagementNodesGetParams) {
	notImplemented(w, r)
}

func (s *Server) ManagementNodeDetailApiV2ManagementNodesManagementNodeIdGet(w http.ResponseWriter, r *http.Request, _ openapi_types.UUID, _ ManagementNodeDetailApiV2ManagementNodesManagementNodeIdGetParams) {
	notImplemented(w, r)
}
