// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flow.proto

// Package atlas.conntrack.v1 asks a node to forget the connection-tracking
// entries translated to one dead backend.
//
// The operator is the caller and the CSI node plugin serves it, on the host's
// network. It is a separate service from atlas.storage.v1, which is read-only
// by construction: this one changes the host's state, so a credential can be
// granted the reading and not this.

package conntrackv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForgetFlowsRequest names the flows, and nothing broader.
type ForgetFlowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP protocol number: 6 for TCP, 17 for UDP.
	Protocol uint32 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Destination port the client connected to, before translation.
	DstPort uint32 `protobuf:"varint,2,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	// Address the flows were translated to: the dead backend.
	ReplySource string `protobuf:"bytes,3,opt,name=reply_source,json=replySource,proto3" json:"reply_source,omitempty"`
	// Address the client connected to, before translation: the Service's
	// ClusterIP. Required, because a dead backend's address can be reused by a
	// pod behind another Service.
	OrigDst       string `protobuf:"bytes,4,opt,name=orig_dst,json=origDst,proto3" json:"orig_dst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetFlowsRequest) Reset() {
	*x = ForgetFlowsRequest{}
	mi := &file_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetFlowsRequest) ProtoMessage() {}

func (x *ForgetFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetFlowsRequest.ProtoReflect.Descriptor instead.
func (*ForgetFlowsRequest) Descriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{0}
}

func (x *ForgetFlowsRequest) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *ForgetFlowsRequest) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *ForgetFlowsRequest) GetReplySource() string {
	if x != nil {
		return x.ReplySource
	}
	return ""
}

func (x *ForgetFlowsRequest) GetOrigDst() string {
	if x != nil {
		return x.OrigDst
	}
	return ""
}

// ForgetFlowsResponse says how many entries were deleted.
type ForgetFlowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       uint64                 `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetFlowsResponse) Reset() {
	*x = ForgetFlowsResponse{}
	mi := &file_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetFlowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetFlowsResponse) ProtoMessage() {}

func (x *ForgetFlowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetFlowsResponse.ProtoReflect.Descriptor instead.
func (*ForgetFlowsResponse) Descriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{1}
}

func (x *ForgetFlowsResponse) GetDeleted() uint64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_flow_proto protoreflect.FileDescriptor

const file_flow_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"flow.proto\x12\x12atlas.conntrack.v1\"\x89\x01\n" +
	"\x12ForgetFlowsRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x19\n" +
	"\bdst_port\x18\x02 \x01(\rR\adstPort\x12!\n" +
	"\freply_source\x18\x03 \x01(\tR\vreplySource\x12\x19\n" +
	"\borig_dst\x18\x04 \x01(\tR\aorigDst\"/\n" +
	"\x13ForgetFlowsResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x04R\adeleted2m\n" +
	"\vFlowService\x12^\n" +
	"\vForgetFlows\x12&.atlas.conntrack.v1.ForgetFlowsRequest\x1a'.atlas.conntrack.v1.ForgetFlowsResponseBMZKgithub.com/simplyblock/atlas/conntrack/conntrackrpc/conntrackv1;conntrackv1b\x06proto3"

var (
	file_flow_proto_rawDescOnce sync.Once
	file_flow_proto_rawDescData []byte
)

func file_flow_proto_rawDescGZIP() []byte {
	file_flow_proto_rawDescOnce.Do(func() {
		file_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_proto_rawDesc), len(file_flow_proto_rawDesc)))
	})
	return file_flow_proto_rawDescData
}

var file_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_flow_proto_goTypes = []any{
	(*ForgetFlowsRequest)(nil),  // 0: atlas.conntrack.v1.ForgetFlowsRequest
	(*ForgetFlowsResponse)(nil), // 1: atlas.conntrack.v1.ForgetFlowsResponse
}
var file_flow_proto_depIdxs = []int32{
	0, // 0: atlas.conntrack.v1.FlowService.ForgetFlows:input_type -> atlas.conntrack.v1.ForgetFlowsRequest
	1, // 1: atlas.conntrack.v1.FlowService.ForgetFlows:output_type -> atlas.conntrack.v1.ForgetFlowsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flow_proto_init() }
func file_flow_proto_init() {
	if File_flow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_proto_rawDesc), len(file_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flow_proto_goTypes,
		DependencyIndexes: file_flow_proto_depIdxs,
		MessageInfos:      file_flow_proto_msgTypes,
	}.Build()
	File_flow_proto = out.File
	file_flow_proto_goTypes = nil
	file_flow_proto_depIdxs = nil
}
