// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: flow.proto

// Package atlas.conntrack.v1 asks a node to forget the connection-tracking
// entries translated to one dead backend.
//
// The operator is the caller and the CSI node plugin serves it, on the host's
// network. It is a separate service from atlas.storage.v1, which is read-only
// by construction: this one changes the host's state, so a credential can be
// granted the reading and not this.

package conntrackv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlowService_ForgetFlows_FullMethodName = "/atlas.conntrack.v1.FlowService/ForgetFlows"
)

// FlowServiceClient is the client API for FlowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FlowService forgets flows on the node it runs on.
type FlowServiceClient interface {
	// ForgetFlows deletes the host's conntrack entries of one protocol and
	// original destination port whose reply source is one address. Nothing
	// matching is success with a count of zero, because the caller repeats the
	// call and the entries may already have expired.
	ForgetFlows(ctx context.Context, in *ForgetFlowsRequest, opts ...grpc.CallOption) (*ForgetFlowsResponse, error)
}

type flowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowServiceClient(cc grpc.ClientConnInterface) FlowServiceClient {
	return &flowServiceClient{cc}
}

func (c *flowServiceClient) ForgetFlows(ctx context.Context, in *ForgetFlowsRequest, opts ...grpc.CallOption) (*ForgetFlowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetFlowsResponse)
	err := c.cc.Invoke(ctx, FlowService_ForgetFlows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowServiceServer is the server API for FlowService service.
// All implementations must embed UnimplementedFlowServiceServer
// for forward compatibility.
//
// FlowService forgets flows on the node it runs on.
type FlowServiceServer interface {
	// ForgetFlows deletes the host's conntrack entries of one protocol and
	// original destination port whose reply source is one address. Nothing
	// matching is success with a count of zero, because the caller repeats the
	// call and the entries may already have expired.
	ForgetFlows(context.Context, *ForgetFlowsRequest) (*ForgetFlowsResponse, error)
	mustEmbedUnimplementedFlowServiceServer()
}

// UnimplementedFlowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowServiceServer struct{}

func (UnimplementedFlowServiceServer) ForgetFlows(context.Context, *ForgetFlowsRequest) (*ForgetFlowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgetFlows not implemented")
}
func (UnimplementedFlowServiceServer) mustEmbedUnimplementedFlowServiceServer() {}
func (UnimplementedFlowServiceServer) testEmbeddedByValue()                     {}

// UnsafeFlowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowServiceServer will
// result in compilation errors.
type UnsafeFlowServiceServer interface {
	mustEmbedUnimplementedFlowServiceServer()
}

func RegisterFlowServiceServer(s grpc.ServiceRegistrar, srv FlowServiceServer) {
	// If the following call panics, it indicates UnimplementedFlowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlowService_ServiceDesc, srv)
}

func _FlowService_ForgetFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowServiceServer).ForgetFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlowService_ForgetFlows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowServiceServer).ForgetFlows(ctx, req.(*ForgetFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlowService_ServiceDesc is the grpc.ServiceDesc for FlowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.conntrack.v1.FlowService",
	HandlerType: (*FlowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForgetFlows",
			Handler:    _FlowService_ForgetFlows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flow.proto",
}
