## Append samples of your project ##
resources:
- storage_v1alpha1_storagecluster.yaml
- storage_v1alpha1_storagenode.yaml
- storage_v1alpha1_pool.yaml
- storage_v1alpha1_task.yaml
- storage_v1alpha1_snapshotreplication.yaml
- storage_v1alpha1_storagebackup.yaml
- storage_v1alpha1_backuprestore.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
