apiVersion: simplyblock.simplyblock.io/v1alpha1
kind: SimplyBlockBackup
metadata:
  labels:
    app.kubernetes.io/name: simplyblock-manager
    app.kubernetes.io/managed-by: kustomize
  name: simplyblockbackup-sample
spec:
  clusterName: sample-cluster
  poolName: sample-pool
  source:
    volumeRef:
      name: sample-volume
  snapshot:
    retain: false
