apiVersion: simplyblock.simplyblock.io/v1alpha1
kind: SimplyBlockStorageCluster
metadata:
  labels:
    app.kubernetes.io/name: simplyblock-manager
    app.kubernetes.io/managed-by: kustomize
  name: simplyblockstoragecluster-sample
spec:
  clusterName: sample-cluster
  useBackup:
    access_key_id: username
    secret_access_key: password
    local_endpoint: http://10.10.11.10:9000
    snapshot_backups: true
    with_compression: false
    secondary_target: 0
    local_testing: true
