apiVersion: storage.simplyblock.io/v1alpha1
kind: Lvol
metadata:
  labels:
    app.kubernetes.io/name: simplyblock-manager
    app.kubernetes.io/managed-by: kustomize
  name: lvol-sample
spec:
  # TODO(user): Add fields here
