apiVersion: storage.simplyblock.io/v1alpha1
kind: StorageNode
metadata:
  labels:
    app.kubernetes.io/name: simplyblock-operator
    app.kubernetes.io/managed-by: kustomize
  name: storagenode-sample
spec:
  # TODO(user): Add fields here
