//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pool) DeepCopyInto(out *Pool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pool.
func (in *Pool) DeepCopy() *Pool {
	if in == nil {
		return nil
	}
	out := new(Pool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolList) DeepCopyInto(out *PoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolList.
func (in *PoolList) DeepCopy() *PoolList {
	if in == nil {
		return nil
	}
	out := new(PoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolSpec) DeepCopyInto(out *PoolSpec) {
	*out = *in
	if in.QoSIOPSLimit != nil {
		in, out := &in.QoSIOPSLimit, &out.QoSIOPSLimit
		*out = new(int32)
		**out = **in
	}
	if in.RWLimit != nil {
		in, out := &in.RWLimit, &out.RWLimit
		*out = new(int32)
		**out = **in
	}
	if in.RLimit != nil {
		in, out := &in.RLimit, &out.RLimit
		*out = new(int32)
		**out = **in
	}
	if in.WLimit != nil {
		in, out := &in.WLimit, &out.WLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolSpec.
func (in *PoolSpec) DeepCopy() *PoolSpec {
	if in == nil {
		return nil
	}
	out := new(PoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolStatus) DeepCopyInto(out *PoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolStatus.
func (in *PoolStatus) DeepCopy() *PoolStatus {
	if in == nil {
		return nil
	}
	out := new(PoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyBlockStorageCluster) DeepCopyInto(out *SimplyBlockStorageCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyBlockStorageCluster.
func (in *SimplyBlockStorageCluster) DeepCopy() *SimplyBlockStorageCluster {
	if in == nil {
		return nil
	}
	out := new(SimplyBlockStorageCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimplyBlockStorageCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyBlockStorageClusterList) DeepCopyInto(out *SimplyBlockStorageClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SimplyBlockStorageCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyBlockStorageClusterList.
func (in *SimplyBlockStorageClusterList) DeepCopy() *SimplyBlockStorageClusterList {
	if in == nil {
		return nil
	}
	out := new(SimplyBlockStorageClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SimplyBlockStorageClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyBlockStorageClusterSpec) DeepCopyInto(out *SimplyBlockStorageClusterSpec) {
	*out = *in
	if in.EnableNodeAffinity != nil {
		in, out := &in.EnableNodeAffinity, &out.EnableNodeAffinity
		*out = new(bool)
		**out = **in
	}
	if in.StripeWdata != nil {
		in, out := &in.StripeWdata, &out.StripeWdata
		*out = new(int32)
		**out = **in
	}
	if in.StripeWparity != nil {
		in, out := &in.StripeWparity, &out.StripeWparity
		*out = new(int32)
		**out = **in
	}
	if in.IsSingleNode != nil {
		in, out := &in.IsSingleNode, &out.IsSingleNode
		*out = new(bool)
		**out = **in
	}
	if in.StrictNodeAntiAffinity != nil {
		in, out := &in.StrictNodeAntiAffinity, &out.StrictNodeAntiAffinity
		*out = new(bool)
		**out = **in
	}
	if in.QpairCount != nil {
		in, out := &in.QpairCount, &out.QpairCount
		*out = new(int32)
		**out = **in
	}
	if in.DistrBs != nil {
		in, out := &in.DistrBs, &out.DistrBs
		*out = new(int32)
		**out = **in
	}
	if in.DistrChunkBs != nil {
		in, out := &in.DistrChunkBs, &out.DistrChunkBs
		*out = new(int32)
		**out = **in
	}
	if in.BlkSize != nil {
		in, out := &in.BlkSize, &out.BlkSize
		*out = new(int32)
		**out = **in
	}
	if in.PageSizeInBlocks != nil {
		in, out := &in.PageSizeInBlocks, &out.PageSizeInBlocks
		*out = new(int32)
		**out = **in
	}
	if in.MaxQueueSize != nil {
		in, out := &in.MaxQueueSize, &out.MaxQueueSize
		*out = new(int32)
		**out = **in
	}
	if in.InflightIOThreshold != nil {
		in, out := &in.InflightIOThreshold, &out.InflightIOThreshold
		*out = new(int32)
		**out = **in
	}
	if in.CapWarn != nil {
		in, out := &in.CapWarn, &out.CapWarn
		*out = new(int32)
		**out = **in
	}
	if in.CapCrit != nil {
		in, out := &in.CapCrit, &out.CapCrit
		*out = new(int32)
		**out = **in
	}
	if in.ProvCapWarn != nil {
		in, out := &in.ProvCapWarn, &out.ProvCapWarn
		*out = new(int32)
		**out = **in
	}
	if in.ProvCapCrit != nil {
		in, out := &in.ProvCapCrit, &out.ProvCapCrit
		*out = new(int32)
		**out = **in
	}
	if in.ClientQpairCount != nil {
		in, out := &in.ClientQpairCount, &out.ClientQpairCount
		*out = new(int32)
		**out = **in
	}
	if in.IncludeStats != nil {
		in, out := &in.IncludeStats, &out.IncludeStats
		*out = new(bool)
		**out = **in
	}
	if in.StatsHistoryInSeconds != nil {
		in, out := &in.StatsHistoryInSeconds, &out.StatsHistoryInSeconds
		*out = new(int32)
		**out = **in
	}
	if in.IncludeEventLog != nil {
		in, out := &in.IncludeEventLog, &out.IncludeEventLog
		*out = new(bool)
		**out = **in
	}
	if in.EventLogEntries != nil {
		in, out := &in.EventLogEntries, &out.EventLogEntries
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyBlockStorageClusterSpec.
func (in *SimplyBlockStorageClusterSpec) DeepCopy() *SimplyBlockStorageClusterSpec {
	if in == nil {
		return nil
	}
	out := new(SimplyBlockStorageClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimplyBlockStorageClusterStatus) DeepCopyInto(out *SimplyBlockStorageClusterStatus) {
	*out = *in
	if in.Health != nil {
		in, out := &in.Health, &out.Health
		*out = new(bool)
		**out = **in
	}
	if in.MgmtNodes != nil {
		in, out := &in.MgmtNodes, &out.MgmtNodes
		*out = new(int32)
		**out = **in
	}
	if in.StorageNodes != nil {
		in, out := &in.StorageNodes, &out.StorageNodes
		*out = new(int32)
		**out = **in
	}
	if in.Rebalancing != nil {
		in, out := &in.Rebalancing, &out.Rebalancing
		*out = new(bool)
		**out = **in
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimplyBlockStorageClusterStatus.
func (in *SimplyBlockStorageClusterStatus) DeepCopy() *SimplyBlockStorageClusterStatus {
	if in == nil {
		return nil
	}
	out := new(SimplyBlockStorageClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageNode) DeepCopyInto(out *StorageNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageNode.
func (in *StorageNode) DeepCopy() *StorageNode {
	if in == nil {
		return nil
	}
	out := new(StorageNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageNodeList) DeepCopyInto(out *StorageNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageNodeList.
func (in *StorageNodeList) DeepCopy() *StorageNodeList {
	if in == nil {
		return nil
	}
	out := new(StorageNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageNodeSpec) DeepCopyInto(out *StorageNodeSpec) {
	*out = *in
	if in.UseSeparateJournalDevice != nil {
		in, out := &in.UseSeparateJournalDevice, &out.UseSeparateJournalDevice
		*out = new(bool)
		**out = **in
	}
	if in.MaxLVol != nil {
		in, out := &in.MaxLVol, &out.MaxLVol
		*out = new(int32)
		**out = **in
	}
	if in.CoreIsolation != nil {
		in, out := &in.CoreIsolation, &out.CoreIsolation
		*out = new(bool)
		**out = **in
	}
	if in.CorePercentage != nil {
		in, out := &in.CorePercentage, &out.CorePercentage
		*out = new(int32)
		**out = **in
	}
	if in.PcieAllowList != nil {
		in, out := &in.PcieAllowList, &out.PcieAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PcieDenyList != nil {
		in, out := &in.PcieDenyList, &out.PcieDenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SocketsToUse != nil {
		in, out := &in.SocketsToUse, &out.SocketsToUse
		*out = new(int32)
		**out = **in
	}
	if in.NodesPerSocket != nil {
		in, out := &in.NodesPerSocket, &out.NodesPerSocket
		*out = new(int32)
		**out = **in
	}
	if in.DataNIC != nil {
		in, out := &in.DataNIC, &out.DataNIC
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HaJmCount != nil {
		in, out := &in.HaJmCount, &out.HaJmCount
		*out = new(int32)
		**out = **in
	}
	if in.WorkerNodes != nil {
		in, out := &in.WorkerNodes, &out.WorkerNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AddPcieToAllowList != nil {
		in, out := &in.AddPcieToAllowList, &out.AddPcieToAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Force != nil {
		in, out := &in.Force, &out.Force
		*out = new(bool)
		**out = **in
	}
	if in.IncludeStats != nil {
		in, out := &in.IncludeStats, &out.IncludeStats
		*out = new(bool)
		**out = **in
	}
	if in.StatsHistoryInSeconds != nil {
		in, out := &in.StatsHistoryInSeconds, &out.StatsHistoryInSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageNodeSpec.
func (in *StorageNodeSpec) DeepCopy() *StorageNodeSpec {
	if in == nil {
		return nil
	}
	out := new(StorageNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageNodeStatus) DeepCopyInto(out *StorageNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageNodeStatus.
func (in *StorageNodeStatus) DeepCopy() *StorageNodeStatus {
	if in == nil {
		return nil
	}
	out := new(StorageNodeStatus)
	in.DeepCopyInto(out)
	return out
}
