#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELM_CHARTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
if [[ -z "${1:-}" ]]; then
  echo "Usage: $0 <operator-dir>" >&2
  exit 1
fi
OPERATOR_DIR="$1"

CRD_SRC="$OPERATOR_DIR/config/crd/bases"
CRD_DST="$HELM_CHARTS_DIR/charts/simplyblock-operator/crds"
RBAC_SRC="$OPERATOR_DIR/config/rbac"
ROLES_DST="$HELM_CHARTS_DIR/charts/simplyblock-operator/templates/roles"

echo "Syncing from: $OPERATOR_DIR"
echo ""

# ── CRDs ──────────────────────────────────────────────────────────────────────
echo "==> Syncing CRDs..."
for src in "$CRD_SRC"/storage.simplyblock.io_*.yaml; do
  name=$(basename "$src")
  cp "$src" "$CRD_DST/$name"
  echo "  copied: $name"
done

# ── Roles ─────────────────────────────────────────────────────────────────────
echo ""
echo "==> Syncing roles..."
mkdir -p "$ROLES_DST"

# Clear stale role files not present in the source.
# manager_role.yaml is generated from role.yaml (different source name), so exclude it from stale removal.
for dst in "$ROLES_DST"/*.yaml; do
  [ -f "$dst" ] || continue
  name=$(basename "$dst")
  [ "$name" = "manager_role.yaml" ] && continue
  [ -f "$RBAC_SRC/$name" ] || { rm "$dst"; echo "  removed (no longer in source): $name"; }
done

# Excluded: leader_election_role and role_binding are managed in simplyblock-operator.yaml
EXCLUDE="leader_election_role.yaml|leader_election_role_binding.yaml|role_binding.yaml|service_account.yaml|kustomization.yaml"

for src in "$RBAC_SRC"/*_role.yaml "$RBAC_SRC"/*_role_binding.yaml; do
  [ -f "$src" ] || continue
  name=$(basename "$src")
  echo "$name" | grep -qE "$EXCLUDE" && continue

  # Normalize: replace kustomize label with Helm, fix known typos
  sed \
    -e 's|app.kubernetes.io/managed-by: kustomize|app.kubernetes.io/managed-by: Helm|g' \
    -e 's|name: ssimplyblocktoragenode-editor-role|name: storagenode-editor-role|g' \
    "$src" > "$ROLES_DST/$name"
  echo "  copied: $name"
done

# ── Manager ClusterRole ────────────────────────────────────────────────────────
# role.yaml is the authoritative source generated by `make manifests` from
# +kubebuilder:rbac annotations. Sync it as a separate ClusterRole so that
# adding a new CRD only requires running this script — no manual edits to
# simplyblock-operator.yaml.
echo ""
echo "==> Syncing manager ClusterRole (from role.yaml)..."
sed \
  -e 's|app.kubernetes.io/managed-by: kustomize|app.kubernetes.io/managed-by: Helm|g' \
  -e 's|name: manager-role|name: simplyblock-operator-manager-role|g' \
  "$RBAC_SRC/role.yaml" > "$ROLES_DST/manager_role.yaml"
echo "  copied: manager_role.yaml (from role.yaml)"

