apiVersion: simplyblock.simplyblock.io/v1alpha1
kind: StorageNode
metadata:
  name: example-node
  namespace: simplyblock
spec:
  clusterName: demo-cluster
  clusterImage: public.ecr.aws/simply-block/simplyblock:25.10.4
  mgmtIfc: eth0
  maxLVol: 100
  maxSnapshots: 128
  statsHistoryInSeconds: 300

  maxSize: 0G

  spdkDebug: false
  includeStats: true
  testDevice: false
  coreIsolation: false
  fullPageUnmap: true

  workerNodes:
    - "vm02.simplyblock3.localdomain"
    - "vm03.simplyblock3.localdomain"
    - "vm04.simplyblock3.localdomain"
