// Renders the add-on template from the Go that defines its contents.
//
// The template is what a member receives, and the objects inside it are built by
// internal/guard rather than written here, so the rule the tests exercise and the
// rule a member installs are one definition. Hand-maintaining both is how a
// policy that passes its suite reaches a cluster in a shape nothing evaluated.
//
// Run through `make addon-manifests`, and commit what it writes. CI fails on the
// diff, which is the same arrangement the generated CustomResourceDefinitions
// are under.

package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/yaml"

	addonv1alpha1 "open-cluster-management.io/api/addon/v1alpha1"
	workv1 "open-cluster-management.io/api/work/v1"

	"github.com/simplyblock/fleet/internal/guard"
)

// version is the add-on's, and it is part of the template's name because a
// ClusterManagementAddOn names the template it defaults to and a rollout is a
// new template beside the old one.
const version = "0.1.0"

// header is what the generated file opens with, since a reader arrives at the
// YAML rather than at this program.
const header = `# The simplyblock fleet add-on, as an Open Cluster Management AddOnTemplate.
#
# Generated by hack/gen-addon from internal/guard. Do not edit: run
# ` + "`make addon-manifests`" + ` and commit the result.
#
# The template is what a member actually receives. OCM's own addon-manager
# renders it into a ManifestWork per enrolled member, so the add-on needs no
# hub-side controller of ours and no second delivery mechanism beside the one the
# deployments already use.
#
# Today, it carries the admission guard and nothing else. The fleet agent joins it
# as a Deployment, a ServiceAccount, and a KubeClient registration stanza when it
# is built, which is a template edit rather than a new mechanism, and is the
# reason the add-on is declared now rather than when the agent exists.
#
# The allowlist here is the default one. A member whose operator runs somewhere
# the default does not name receives a composed list instead, delivered in the
# same payload.
#
# Nothing here reaches a standalone installation. A standalone cluster runs no
# add-on, so it receives no policy, and its admission configuration is what it
# was before a fleet existed.
`

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-addon:", err)
		os.Exit(1)
	}
}

func run() error {
	list := guard.DefaultAllowlist()
	if err := list.Validate(); err != nil {
		return fmt.Errorf("the default allowlist does not validate: %w", err)
	}

	manifests := make([]workv1.Manifest, 0, 3)
	for _, object := range guard.Objects(list) {
		encoded, err := yaml.Marshal(object)
		if err != nil {
			return fmt.Errorf("encoding %T: %w", object, err)
		}
		asJSON, err := yaml.YAMLToJSON(encoded)
		if err != nil {
			return fmt.Errorf("re-encoding %T: %w", object, err)
		}
		manifests = append(manifests, workv1.Manifest{RawExtension: runtime.RawExtension{Raw: asJSON}})
	}

	template := &addonv1alpha1.AddOnTemplate{
		TypeMeta: metav1.TypeMeta{
			APIVersion: addonv1alpha1.GroupVersion.String(),
			Kind:       "AddOnTemplate",
		},
		ObjectMeta: metav1.ObjectMeta{Name: "simplyblock-fleet-" + version},
		Spec: addonv1alpha1.AddOnTemplateSpec{
			AddonName: "simplyblock-fleet",
			AgentSpec: workv1.ManifestWorkSpec{
				Workload: workv1.ManifestsTemplate{Manifests: manifests},
			},
		},
	}

	encoded, err := yaml.Marshal(template)
	if err != nil {
		return fmt.Errorf("encoding the template: %w", err)
	}

	var out bytes.Buffer
	out.WriteString(header)
	out.Write(encoded)

	path := filepath.Join("config", "addon", "addontemplate.yaml")
	if err := os.WriteFile(path, out.Bytes(), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	fmt.Println("wrote", path)
	return nil
}
