apiVersion: storage.simplyblock.io/v1alpha1
kind: StorageNodeSet
metadata:
  labels:
    app.kubernetes.io/name: simplyblock-operator
    app.kubernetes.io/managed-by: kustomize
  name: storagenodeset-sample
spec:
  clusterName: sample-cluster
  clusterImage: quay.io/simplyblock-io/simplyblock:26.2.5-PRE@sha256:07a9fb4404e63e8a6b86e35e91cdc2db448e776756f609a5b3fe9a02556e447d
  workerNodes:
    - worker-node-1
