apiVersion: storage.simplyblock.io/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: simplyblock-operator
    app.kubernetes.io/managed-by: kustomize
  name: task-sample
spec:
  clusterName: sample-cluster
