{{- if .Values.operator.enabled }}
---
apiVersion: storage.simplyblock.io/v1alpha1
kind: ControlPlane
metadata:
  name: simplyblock
  namespace: {{ .Release.Namespace }}
spec:
  image: "{{ .Values.image.simplyblock.repository }}:{{ .Values.image.simplyblock.tag }}"
{{- end }}
