// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: export.proto

// Package atlas.export.v1 carries pNFS export assembly to the host that serves
// it.
//
// Unlike atlas.storage.v1, which is read-only by construction, everything here
// mutates the node: it makes filesystems, mounts them, and publishes them. That
// is why it is a separate service rather than more methods on the storage one --
// a credential can be granted the reading and not the writing.
//
// The operator is the only caller. No consuming pod runs on the host that serves
// an export, so kubelet never issues a stage for it and something else has to
// ask; this is that something.

package exportv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExportSpec is one export: which device, where it goes, and who may mount it.
// It mirrors export.Spec field for field.
type ExportSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// volume_uuid identifies the backing namespace: for a simplyblock volume the
	// namespace UUID is the logical volume's own id. It is the identifier rather
	// than a device path because a path is assigned in attach order and differs
	// across hosts, while this is a property of the namespace.
	//
	// It is the UUID rather than the NGUID because the UUID is what the control
	// plane knows when it provisions; the NGUID is assigned by the target and
	// read back from the device.
	VolumeUuid string `protobuf:"bytes,1,opt,name=volume_uuid,json=volumeUuid,proto3" json:"volume_uuid,omitempty"`
	// path is the mount point and the exported directory.
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// fsid is what the export is published under. Holding it stable across hosts
	// is what lets a re-materialized export reproduce the file handles clients
	// already hold.
	Fsid string `protobuf:"bytes,3,opt,name=fsid,proto3" json:"fsid,omitempty"`
	// clients is the set allowed to mount, as exports(5) spells it. An empty set
	// is refused rather than widened to everyone.
	Clients []string `protobuf:"bytes,4,rep,name=clients,proto3" json:"clients,omitempty"`
	// cluster_id and pool_id identify the volume to the control plane, which is
	// what the host needs to ask where the namespace is served from and to be
	// allowed to connect to it. They do not find the device -- volume_uuid does
	// that -- and a host that does not attach its own namespaces ignores them.
	ClusterId string `protobuf:"bytes,5,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	PoolId    string `protobuf:"bytes,6,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	// encrypted tells the assembler to open the backing namespace before
	// inspecting or formatting its filesystem.
	Encrypted     bool `protobuf:"varint,7,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSpec) Reset() {
	*x = ExportSpec{}
	mi := &file_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSpec) ProtoMessage() {}

func (x *ExportSpec) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSpec.ProtoReflect.Descriptor instead.
func (*ExportSpec) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportSpec) GetVolumeUuid() string {
	if x != nil {
		return x.VolumeUuid
	}
	return ""
}

func (x *ExportSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ExportSpec) GetFsid() string {
	if x != nil {
		return x.Fsid
	}
	return ""
}

func (x *ExportSpec) GetClients() []string {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ExportSpec) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ExportSpec) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *ExportSpec) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

type CreateExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ExportSpec            `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExportRequest) Reset() {
	*x = CreateExportRequest{}
	mi := &file_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExportRequest) ProtoMessage() {}

func (x *CreateExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExportRequest.ProtoReflect.Descriptor instead.
func (*CreateExportRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExportRequest) GetSpec() *ExportSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExportResponse) Reset() {
	*x = CreateExportResponse{}
	mi := &file_export_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExportResponse) ProtoMessage() {}

func (x *CreateExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExportResponse.ProtoReflect.Descriptor instead.
func (*CreateExportResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{2}
}

type DeleteExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ExportSpec            `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExportRequest) Reset() {
	*x = DeleteExportRequest{}
	mi := &file_export_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExportRequest) ProtoMessage() {}

func (x *DeleteExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExportRequest.ProtoReflect.Descriptor instead.
func (*DeleteExportRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteExportRequest) GetSpec() *ExportSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type DeleteExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExportResponse) Reset() {
	*x = DeleteExportResponse{}
	mi := &file_export_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExportResponse) ProtoMessage() {}

func (x *DeleteExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExportResponse.ProtoReflect.Descriptor instead.
func (*DeleteExportResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{4}
}

type CheckExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *ExportSpec            `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExportRequest) Reset() {
	*x = CheckExportRequest{}
	mi := &file_export_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExportRequest) ProtoMessage() {}

func (x *CheckExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExportRequest.ProtoReflect.Descriptor instead.
func (*CheckExportRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{5}
}

func (x *CheckExportRequest) GetSpec() *ExportSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CheckExportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy is false whenever the node found a reason the export is not
	// actually being served. reason says which.
	Healthy       bool   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckExportResponse) Reset() {
	*x = CheckExportResponse{}
	mi := &file_export_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExportResponse) ProtoMessage() {}

func (x *CheckExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExportResponse.ProtoReflect.Descriptor instead.
func (*CheckExportResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{6}
}

func (x *CheckExportResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *CheckExportResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_export_proto protoreflect.FileDescriptor

const file_export_proto_rawDesc = "" +
	"\n" +
	"\fexport.proto\x12\x0fatlas.export.v1\"\xc5\x01\n" +
	"\n" +
	"ExportSpec\x12\x1f\n" +
	"\vvolume_uuid\x18\x01 \x01(\tR\n" +
	"volumeUuid\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04fsid\x18\x03 \x01(\tR\x04fsid\x12\x18\n" +
	"\aclients\x18\x04 \x03(\tR\aclients\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x05 \x01(\tR\tclusterId\x12\x17\n" +
	"\apool_id\x18\x06 \x01(\tR\x06poolId\x12\x1c\n" +
	"\tencrypted\x18\a \x01(\bR\tencrypted\"F\n" +
	"\x13CreateExportRequest\x12/\n" +
	"\x04spec\x18\x01 \x01(\v2\x1b.atlas.export.v1.ExportSpecR\x04spec\"\x16\n" +
	"\x14CreateExportResponse\"F\n" +
	"\x13DeleteExportRequest\x12/\n" +
	"\x04spec\x18\x01 \x01(\v2\x1b.atlas.export.v1.ExportSpecR\x04spec\"\x16\n" +
	"\x14DeleteExportResponse\"E\n" +
	"\x12CheckExportRequest\x12/\n" +
	"\x04spec\x18\x01 \x01(\v2\x1b.atlas.export.v1.ExportSpecR\x04spec\"G\n" +
	"\x13CheckExportResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xa3\x02\n" +
	"\rExportService\x12[\n" +
	"\fCreateExport\x12$.atlas.export.v1.CreateExportRequest\x1a%.atlas.export.v1.CreateExportResponse\x12[\n" +
	"\fDeleteExport\x12$.atlas.export.v1.DeleteExportRequest\x1a%.atlas.export.v1.DeleteExportResponse\x12X\n" +
	"\vCheckExport\x12#.atlas.export.v1.CheckExportRequest\x1a$.atlas.export.v1.CheckExportResponseBAZ?github.com/simplyblock/atlas/export/exportrpc/exportv1;exportv1b\x06proto3"

var (
	file_export_proto_rawDescOnce sync.Once
	file_export_proto_rawDescData []byte
)

func file_export_proto_rawDescGZIP() []byte {
	file_export_proto_rawDescOnce.Do(func() {
		file_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)))
	})
	return file_export_proto_rawDescData
}

var file_export_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_export_proto_goTypes = []any{
	(*ExportSpec)(nil),           // 0: atlas.export.v1.ExportSpec
	(*CreateExportRequest)(nil),  // 1: atlas.export.v1.CreateExportRequest
	(*CreateExportResponse)(nil), // 2: atlas.export.v1.CreateExportResponse
	(*DeleteExportRequest)(nil),  // 3: atlas.export.v1.DeleteExportRequest
	(*DeleteExportResponse)(nil), // 4: atlas.export.v1.DeleteExportResponse
	(*CheckExportRequest)(nil),   // 5: atlas.export.v1.CheckExportRequest
	(*CheckExportResponse)(nil),  // 6: atlas.export.v1.CheckExportResponse
}
var file_export_proto_depIdxs = []int32{
	0, // 0: atlas.export.v1.CreateExportRequest.spec:type_name -> atlas.export.v1.ExportSpec
	0, // 1: atlas.export.v1.DeleteExportRequest.spec:type_name -> atlas.export.v1.ExportSpec
	0, // 2: atlas.export.v1.CheckExportRequest.spec:type_name -> atlas.export.v1.ExportSpec
	1, // 3: atlas.export.v1.ExportService.CreateExport:input_type -> atlas.export.v1.CreateExportRequest
	3, // 4: atlas.export.v1.ExportService.DeleteExport:input_type -> atlas.export.v1.DeleteExportRequest
	5, // 5: atlas.export.v1.ExportService.CheckExport:input_type -> atlas.export.v1.CheckExportRequest
	2, // 6: atlas.export.v1.ExportService.CreateExport:output_type -> atlas.export.v1.CreateExportResponse
	4, // 7: atlas.export.v1.ExportService.DeleteExport:output_type -> atlas.export.v1.DeleteExportResponse
	6, // 8: atlas.export.v1.ExportService.CheckExport:output_type -> atlas.export.v1.CheckExportResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_export_proto_init() }
func file_export_proto_init() {
	if File_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_export_proto_goTypes,
		DependencyIndexes: file_export_proto_depIdxs,
		MessageInfos:      file_export_proto_msgTypes,
	}.Build()
	File_export_proto = out.File
	file_export_proto_goTypes = nil
	file_export_proto_depIdxs = nil
}
