// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: export.proto

// Package atlas.export.v1 carries pNFS export assembly to the host that serves
// it.
//
// Unlike atlas.storage.v1, which is read-only by construction, everything here
// mutates the node: it makes filesystems, mounts them, and publishes them. That
// is why it is a separate service rather than more methods on the storage one --
// a credential can be granted the reading and not the writing.
//
// The operator is the only caller. No consuming pod runs on the host that serves
// an export, so kubelet never issues a stage for it and something else has to
// ask; this is that something.

package exportv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExportService_CreateExport_FullMethodName = "/atlas.export.v1.ExportService/CreateExport"
	ExportService_DeleteExport_FullMethodName = "/atlas.export.v1.ExportService/DeleteExport"
	ExportService_CheckExport_FullMethodName  = "/atlas.export.v1.ExportService/CheckExport"
)

// ExportServiceClient is the client API for ExportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExportService assembles and tears down exports on the node it runs on. Both
// calls are idempotent, because the caller is a reconciler and will make them
// again.
type ExportServiceClient interface {
	// CreateExport assembles the export: find the device, make a filesystem only
	// if the device is blank, mount it, and publish it. Re-running it over a
	// finished export changes nothing on the host.
	CreateExport(ctx context.Context, in *CreateExportRequest, opts ...grpc.CallOption) (*CreateExportResponse, error)
	// DeleteExport tears it down in reverse. An export that is already gone is
	// success, not an error, because the caller is a finalizer and has to
	// converge.
	DeleteExport(ctx context.Context, in *DeleteExportRequest, opts ...grpc.CallOption) (*DeleteExportResponse, error)
	// CheckExport reports whether the export is actually being served: nfsd has
	// threads running, the filesystem this export sits on is mounted, and
	// nfsd's own table publishes it. It changes nothing on the host -- a probe
	// that could repair what it finds broken would be a second, undeclared path
	// to the same mutations CreateExport already owns.
	CheckExport(ctx context.Context, in *CheckExportRequest, opts ...grpc.CallOption) (*CheckExportResponse, error)
}

type exportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExportServiceClient(cc grpc.ClientConnInterface) ExportServiceClient {
	return &exportServiceClient{cc}
}

func (c *exportServiceClient) CreateExport(ctx context.Context, in *CreateExportRequest, opts ...grpc.CallOption) (*CreateExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExportResponse)
	err := c.cc.Invoke(ctx, ExportService_CreateExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) DeleteExport(ctx context.Context, in *DeleteExportRequest, opts ...grpc.CallOption) (*DeleteExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExportResponse)
	err := c.cc.Invoke(ctx, ExportService_DeleteExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exportServiceClient) CheckExport(ctx context.Context, in *CheckExportRequest, opts ...grpc.CallOption) (*CheckExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckExportResponse)
	err := c.cc.Invoke(ctx, ExportService_CheckExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExportServiceServer is the server API for ExportService service.
// All implementations must embed UnimplementedExportServiceServer
// for forward compatibility.
//
// ExportService assembles and tears down exports on the node it runs on. Both
// calls are idempotent, because the caller is a reconciler and will make them
// again.
type ExportServiceServer interface {
	// CreateExport assembles the export: find the device, make a filesystem only
	// if the device is blank, mount it, and publish it. Re-running it over a
	// finished export changes nothing on the host.
	CreateExport(context.Context, *CreateExportRequest) (*CreateExportResponse, error)
	// DeleteExport tears it down in reverse. An export that is already gone is
	// success, not an error, because the caller is a finalizer and has to
	// converge.
	DeleteExport(context.Context, *DeleteExportRequest) (*DeleteExportResponse, error)
	// CheckExport reports whether the export is actually being served: nfsd has
	// threads running, the filesystem this export sits on is mounted, and
	// nfsd's own table publishes it. It changes nothing on the host -- a probe
	// that could repair what it finds broken would be a second, undeclared path
	// to the same mutations CreateExport already owns.
	CheckExport(context.Context, *CheckExportRequest) (*CheckExportResponse, error)
	mustEmbedUnimplementedExportServiceServer()
}

// UnimplementedExportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExportServiceServer struct{}

func (UnimplementedExportServiceServer) CreateExport(context.Context, *CreateExportRequest) (*CreateExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExport not implemented")
}
func (UnimplementedExportServiceServer) DeleteExport(context.Context, *DeleteExportRequest) (*DeleteExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExport not implemented")
}
func (UnimplementedExportServiceServer) CheckExport(context.Context, *CheckExportRequest) (*CheckExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckExport not implemented")
}
func (UnimplementedExportServiceServer) mustEmbedUnimplementedExportServiceServer() {}
func (UnimplementedExportServiceServer) testEmbeddedByValue()                       {}

// UnsafeExportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExportServiceServer will
// result in compilation errors.
type UnsafeExportServiceServer interface {
	mustEmbedUnimplementedExportServiceServer()
}

func RegisterExportServiceServer(s grpc.ServiceRegistrar, srv ExportServiceServer) {
	// If the following call panics, it indicates UnimplementedExportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExportService_ServiceDesc, srv)
}

func _ExportService_CreateExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).CreateExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_CreateExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).CreateExport(ctx, req.(*CreateExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_DeleteExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).DeleteExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_DeleteExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).DeleteExport(ctx, req.(*DeleteExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExportService_CheckExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExportServiceServer).CheckExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExportService_CheckExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExportServiceServer).CheckExport(ctx, req.(*CheckExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExportService_ServiceDesc is the grpc.ServiceDesc for ExportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "atlas.export.v1.ExportService",
	HandlerType: (*ExportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExport",
			Handler:    _ExportService_CreateExport_Handler,
		},
		{
			MethodName: "DeleteExport",
			Handler:    _ExportService_DeleteExport_Handler,
		},
		{
			MethodName: "CheckExport",
			Handler:    _ExportService_CheckExport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "export.proto",
}
