name: Helm Lint (operator chart)

on:
  push:
    branches:
      - main
    paths:
      - "helm-charts/charts/simplyblock-operator/**"
      - ".github/workflows/ci-operator.yaml"
  pull_request:
    paths:
      - "helm-charts/charts/simplyblock-operator/**"
      - ".github/workflows/ci-operator.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Lint
        run: helm lint helm-charts/charts/simplyblock-operator

      - name: Template
        run: helm template simplyblock-operator helm-charts/charts/simplyblock-operator