name: Lint (operator)

on:
  push:
    branches:
      - main
    paths:
      - "operator/**"
      - ".github/workflows/operator_lint.yaml"
  pull_request:
    paths:
      - "operator/**"
      - ".github/workflows/operator_lint.yaml"

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: operator/go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.11.4
          working-directory: operator